### ISSUE TITLE
Not_Categorized

### ISSUE THREAD

**Issue by D3athAn63l** [shakeyourbunny/RWMSDB#100]
{
 "meta": {
  "contributor": "",
  "mods_known": 169,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.4",
  "time": "Mon May 13 23:02:08 2019"
 },
  "chickens Multiproducer": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=966175947"
  ],
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi, your input file was mangled, could salvage the data though.

Thank you for your contribution!
