### ISSUE TITLE
More fun with CE :( Simple chains: Leather should be loaded after CE

### ISSUE THREAD

**Issue by jpc0** [shakeyourbunny/RWMSDB#103]
Title says it all. Simple Chains: Leather should be loaded after CE.

If you want to feel free to give me a quick breakdown on how to make the edit myself then will do so and send a pull request in future.

**Comment by shakeyourbunny** [comment]
Really, the CE patch should be something extra and not included directly in the patch; because this messes really really much up.

**Comment by shakeyourbunny** [comment]
fixed it, moved "Combat Extended" way up the ladder  to accomodate this.
