### ISSUE TITLE
Unknown Mods by kenderbard

### ISSUE THREAD

**Issue by kenderbard** [shakeyourbunny/RWMSDB#105]
{
 "meta": {
  "contributor": "",
  "mods_known": 17,
  "mods_unknown": 7,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.4",
  "time": "Tue May 14 21:00:11 2019"
 },
 "unknown": {
  "Cannibal Party": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=823179072"
  ],
  "Corpse To Chemfuel": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1735705268"
  ],
  "Emergency Resources": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1728150743"
  ],
  "NaturalFloors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1540857850"
  ],
  "RimNGE": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1687909697"
  ],
  "Smarty Storyteller": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Smarty"
  ],
  "[1.0]Mystery Meat: Feed human meat to colonists!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1412832332"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your mods, have fun!
