### ISSUE TITLE
My Unknow mods

### ISSUE THREAD

**Issue by haziel831** [shakeyourbunny/RWMSDB#109]
[rwms_unknown_mods_20190516-0148.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3185443/rwms_unknown_mods_20190516-0148.json.txt)

**Comment by shakeyourbunny** [comment]
Hello, 

I added your mods - as far as I could locate them on the internet, I had to cut out some.

Please resubmit the missing mods if you like, but I need some download links / descriptions for them (japanese is not a problem).

Thank you!
