### ISSUE TITLE
Unknown

### ISSUE THREAD

**Issue by Deathawaits4** [shakeyourbunny/RWMSDB#11]
[rwms_unknown_mods_20190419-1258.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3097878/rwms_unknown_mods_20190419-1258.json.txt)

**Comment by Deathawaits4** [comment]
Also note that rimquest had to be further on top of the load order, it has to be ontop of Rimwriter or it might behave a bit weird.

**Comment by shakeyourbunny** [comment]
I moved RimQuest from the storyteller category (is very down the categories) up to gameplay mods; this should fix it.
