### ISSUE TITLE
here's a few

### ISSUE THREAD

**Issue by Preechr** [shakeyourbunny/RWMSDB#111]
[rwms_unknown_mods_20190501-2036.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3189082/rwms_unknown_mods_20190501-2036.json.txt)
[rwms_unknown_mods_20190516-1719.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3189083/rwms_unknown_mods_20190516-1719.json.txt)
[rwms_unknown_mods_20190414-1853.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3189084/rwms_unknown_mods_20190414-1853.json.txt)

**Comment by shakeyourbunny** [comment]
Hi,

added your contribution, thank you!

NB: you should upgrade your RWMS soon :)
