### ISSUE TITLE
2 Unknown mods

### ISSUE THREAD

**Issue by D3athAn63l** [shakeyourbunny/RWMSDB#112]
{
	"meta": {
		"contributor": "",
		"mods_known": 187,
		"mods_unknown": 3,
		"os": "win32",
		"rimworld_version": "1.0.2231 rev1144",
		"rwms_version": "0.94.5",
		"time": "Fri May 17 12:16:08 2019"
	},
	"unknown": {
		"Evolved Organs": [
			"not_categorized",
			"https://steamcommunity.com/sharedfiles/filedetails/?id=1742245843"
		],
		"Quick Stockpile Creation": [
			"not_categorized",
			"https://steamcommunity.com/sharedfiles/filedetails/?id=1742151109"
		]
	},
	"version": 2
}

**Comment by shakeyourbunny** [comment]
added your new mods, thank you!
