### ISSUE TITLE
Some Unknown Mods

### ISSUE THREAD

**Issue by TheTangoMoonSpirit** [shakeyourbunny/RWMSDB#113]
[rwms_unknown_mods_20190512-0122.zip](https://github.com/shakeyourbunny/RWMSDB/files/3190182/rwms_unknown_mods_20190512-0122.zip)

**Comment by shakeyourbunny** [comment]
Hello,

please upgrade your RWMS at https://www.github.com/shakeyourbunny/RMWS/releases, you seem to use an old version of the script.

After running a deduper against your contribution, there were no unknown mods present.
