### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by Riley4376** [shakeyourbunny/RWMSDB#115]
UNKNOWN MODS LISTED BELOW AND ATTACHED :)

{
 "meta": {
  "contributor": "",
  "mods_known": 266,
  "mods_unknown": 10,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.5",
  "time": "Fri May 17 14:28:38 2019"
 },
 "unknown": {
  "Assign Prisoner Beds": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=AssignPrisonerBed"
  ],
  "CPBeasties": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=768448143"
  ],
  "CTS - Complete Tech Solutions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=792364419"
  ],
  "Dead Goat's Weapon Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=728503320"
  ],
  "Doctor Floopills": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1464030696"
  ],
  "ED-CheatReactor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=710101929"
  ],
  "Hardcore Armors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=850073860"
  ],
  "Industrialisation - Glitter Tech Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=918177214"
  ],
  "Medicines+": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1364582731"
  ],
  "[1.0] FuckFriendlyFire": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1013648397"
  ]
 },
 "version": 2
}

[Unknown Mods.ZIP](https://github.com/shakeyourbunny/RWMSDB/files/3192839/Unknown.Mods.ZIP)

**Comment by Riley4376** [comment]
Apologies the first mod was located on the forums. please disregard Assign Prisoner beds :)

**Comment by shakeyourbunny** [comment]
RWMS does wants to know every mod, not just from the workshop.

The autogenerated URL may not work, but there is sadly no way to get a correct URL, the mods itself don't include a homepage URL.

**Comment by shakeyourbunny** [comment]
added your 10 mods, have fun playing!
