### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by TrippyTheO** [shakeyourbunny/RWMSDB#116]
[rwms_unknown_mods_20190517-1439.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3192877/rwms_unknown_mods_20190517-1439.json.txt)

Hopefully I'm doing this correctly, thanks for the awesome mod!

**Comment by TrippyTheO** [comment]
Not sure if best place for this but wanted to point out real quick. RWMS placed Doors Expanded by Jecrell after Cults, and the three Lord Of the Rims races (Elves, Hobbits, Dwarves). The folks on their Discord have always said that DE needs to be loaded before any of those mods, and Fluffys Mod Manager reports the same. 

Not sure if that's an oversight in the mod database or if they're just incorrect.

**Comment by shakeyourbunny** [comment]
Hi,

added your unknown mods. I also integrated your fix request, problem should be solved now afte re-running the script.
