### ISSUE TITLE
1 new mod

### ISSUE THREAD

**Issue by D3athAn63l** [shakeyourbunny/RWMSDB#117]
{
 "meta": {
  "contributor": "",
  "mods_known": 189,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.5",
  "time": "Sat May 18 06:09:25 2019"
 },
 "unknown": {
  "Endgame Buildings": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1743009906"
  ]
 },
 "version": 2
}

bigger database now :D

**Comment by shakeyourbunny** [comment]
Hi, added your mods :-)
