### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by brucethemoose** [shakeyourbunny/RWMSDB#119]
Star Trek Races may or may not already be added, it's a personal edit of the github release. 

meta": {
  "contributor": "",
  "mods_known": 161,
  "mods_unknown": 6,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1155",
  "rwms_version": "0.94.5",
  "time": "Sat May 18 02:41:01 2019"
 },
 "unknown": {
  "Animal Armor Vanilla [OGSN]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1743423205"
  ],
  "Jello People - Combat Extended Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1742748898"
  ],
  "NutritiousKibble0.29": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1334392947"
  ],
  "Quarians!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1704445484"
  ],
  "Star Trek: Races [Just Fed]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Star Trek Races JUST FED"
  ],
  "Subtle variations for RimThemes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1676934872"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
hi, added your contribution, thank you!

the Star Trek Edit seems to be available (at least the name) on steam workshop though ;D
