### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by NKSHV** [shakeyourbunny/RWMSDB#122]
{
 "meta": {
  "contributor": "",
  "mods_known": 249,
  "mods_unknown": 24,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.6",
  "time": "Mon May 20 13:54:29 2019"
 },
 "unknown": {
  "A Better Wholesome Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1118755431"
  ],
  "Advanced Transport Pods ++": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1630948571"
  ],
  "Area Rugs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Area_Rugs"
  ],
  "Beasts of the Rim": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=767300413"
  ],
  "Chemical Substances of Varying Legality": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1721118225"
  ],
  "Doomalope": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=893828016"
  ],
  "Effigy Mod[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1222844735"
  ],
  "Giant Bees": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1381203671"
  ],
  "LED Lamps": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=842019577"
  ],
  "Let's Have a Cat! - Not Train Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1634550349"
  ],
  "M-13's ChemFuel Generators": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541519044"
  ],
  "Miraffe (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541525119"
  ],
  "Multilopes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1498287856"
  ],
  "Pet Cucumber [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541255674"
  ],
  "Pink Material Sheep [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1543522877"
  ],
  "SCP - 111|Dragon Snails [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541255910"
  ],
  "Stronger Sandbags": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1731057189"
  ],
  "Weird Warfare": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1604592543"
  ],
  "Yorkshire Terrors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1556099860"
  ],
  "ZWAnimals": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=838842766"
  ],
  "[1.0]Kan Colle hair style (Female) ": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1721089145"
  ],
  "[1.0]More tools and weapons [andery]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1543671650"
  ],
  "fast regen - Nano Tech Repair": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1738277713"
  ],
  "\u66f4\u591a\u6280\u80fd\u76f8\u5173": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=845593629"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hello, added your contributions :-)
