### ISSUE TITLE
Boop, Another Unknown Mod

### ISSUE THREAD

**Issue by brucethemoose** [shakeyourbunny/RWMSDB#129]
{
 "meta": {
  "contributor": "",
  "mods_known": 2,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.6",
  "time": "Thu May 23 02:56:06 2019"
 },
 "unknown": {
  "BETTER PASTA Blood Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1716386563"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your mod, have fun!
