### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by rawrfisher** [shakeyourbunny/RWMSDB#134]
{
 "meta": {
  "contributor": "",
  "mods_known": 151,
  "mods_unknown": 5,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.6",
  "time": "Fri May 24 16:41:42 2019"
 },
 "unknown": {
  "Desynchronized: Tales and News (v1.5.1)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1573233249"
  ],
  "Kurin CE Pach": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1748066638"
  ],
  "Rimworld of Magic CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1746117682"
  ],
  "Sun Lights (Balanced) [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1530300927"
  ],
  "[RH] Faction: Last Man Mercs (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=(RH) Last Man Mercs (1.0)"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Added your missing mods except "[RH] Faction: Last Man Mercs (1.0)", which I could not find on the web.
