### ISSUE TITLE
unknown mods 

### ISSUE THREAD

**Issue by NKSHV** [shakeyourbunny/RWMSDB#139]
{
 "meta": {
  "contributor": "test",
  "mods_known": 371,
  "mods_unknown": 28,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.6",
  "time": "Sat May 25 11:46:20 2019"
 },
 "unknown": {
  "Anti Material Rifle": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=732511524"
  ],
  "Anti Material Rifle +": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=939667782"
  ],
  "Bionic Weapons Platform": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1725384922"
  ],
  "CIWS_Animal [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1493492960"
  ],
  "CIWS_Bionic [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1493495675"
  ],
  "CIWS_Core [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1493484469"
  ],
  "CIWS_Defense [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1493496244"
  ],
  "CIWS_Miscellaneous [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1493497872"
  ],
  "CIWS_Plant [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1493498713"
  ],
  "CIWS_Power [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1493502590"
  ],
  "ChargedEnergyMunitions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1638608673"
  ],
  "Cutebold Race 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542453511"
  ],
  "Dalek": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1510325200"
  ],
  "ExNeph's Unrealistic Fun Factory": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1743621970"
  ],
  "Gnoll Race 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544268433"
  ],
  "Ikquan Race (Humanoid Fish Alien Race)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1663859834"
  ],
  "Misc. Endgame": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1750618143"
  ],
  "NoRandomDeathOnDown": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1737875243"
  ],
  "Professor's Laboratory of Alchemical Horrors and Fun": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1678535056"
  ],
  "Red Alert 2[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1499370491"
  ],
  "Rimfall: The Frontier (1.5) 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1547881310"
  ],
  "Ruddy Great Guns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1437575067"
  ],
  "Ryndren Augmentations": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1734989263"
  ],
  "Soybeans": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=932373937"
  ],
  "The Zerg!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542306804"
  ],
  "Training Rack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=736584444"
  ],
  "Universal Robot": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1724547143"
  ],
  "[1.0] Advanced Animal Frameworks 3.4": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1336991209"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hello, added your contribution. Thank you!
