### ISSUE TITLE
Unknown Mods by Darwinning

### ISSUE THREAD

**Issue by Darwinning** [shakeyourbunny/RWMSDB#144]
{
 "meta": {
  "contributor": "",
  "mods_known": 269,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2272 rev707",
  "rwms_version": "0.94.2",
  "time": "Sat May 25 20:22:28 2019"
 },
 "unknown": {
  "Desynchronized: Tales and News (v1.5.1)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1573233249"
  ],
  "[1.0] DE Surgeries - Alpha Animals patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1732715130"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your contribution, thank you!

**Comment by Darwinning** [comment]
I ran this again today and they're still showing unknown
