### ISSUE TITLE
My unknown mods

### ISSUE THREAD

**Issue by seriouscylinder** [shakeyourbunny/RWMSDB#15]
Here ya go:
{
 "Confetti": "not_categorized",
 "EPOE Replacement Expansion": "not_categorized",
 "Utility Supplements": "not_categorized",
 "[WD] More Mini-Turrets 1.0": "not_categorized",
 "time": "Tue Apr 23 18:58:52 2019"
}

**Comment by shakeyourbunny** [comment]
Hello, 

I added your unknown mods, have fun!
