### ISSUE TITLE
order error

### ISSUE THREAD

**Issue by pigand** [shakeyourbunny/RWMSDB#150]
i was looking through my load order with mehni's modsorter program and noticed some mods that were left out of order from rwms. 
"ancient rim - core" needs to be above "ancient rim - spqrim" ("ancient rim - mediterranian factions" is in the right place below)
"anesthetic gun mod" needs to be above "anesthetic turret mod"

**Comment by shakeyourbunny** [comment]
Hi, thank you.

Anesthic Gun / Turret: Problem is that both mods were classified as combat mods, so the load order is not set in stone, fixed that so that the turret mod is now an addon of the gun mod.
Ancient Rim: fixed load order
