### ISSUE TITLE
Multiplayer Load Order

### ISSUE THREAD

**Issue by AlphaAtlas** [shakeyourbunny/RWMSDB#152]
The auto mod sorter puts Zethrith's Multiplayer Mod below hugslib, when it should always be the first mod to load, right under Core, according to the mod's instruction pages.

I'm not sure if this actually makes a difference, but Fluffy's Mod Manager complains about the order as well.

**Comment by shakeyourbunny** [comment]
I could not really locate the Multiplay Mod in my database, but I guess it's "Multiplayer". moved this above Hugslib.

Thank you!
