### ISSUE TITLE
unknown mods found by miyoumu

### ISSUE THREAD

**Issue by Miyoumu** [shakeyourbunny/RWMSDB#166]
{
 "meta": {
  "contributor": "miyoumu",
  "mods_known": 192,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Sat Jun  1 16:55:51 2019"
 },
 "unknown": {
  "War Crimes Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=__LocalCopy_War Crimes Expanded_(1-6)"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi, added this mod. Thank you!
