### ISSUE TITLE
unknown mods

### ISSUE THREAD

**Issue by drbodrbo** [shakeyourbunny/RWMSDB#172]
{
 "meta": {
  "contributor": "",
  "mods_known": 133,
  "mods_unknown": 12,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Tue Jun  4 00:08:29 2019"
 },
 "unknown": {
  "A Dog Said...": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=A_Dog_Said-A18"
  ],
  "Barky's Caravan Dogs (for 1.0 & b19)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1497792975"
  ],
  "Boartato Badditions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1448199686"
  ],
  "Dead Can Serve": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1735705268"
  ],
  "Extended Surgery": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1312089354"
  ],
  "MedievalShields": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=728302374"
  ],
  "Megafauna - A Dog Said Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1097287517"
  ],
  "Silent Mechanoids": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1652048515"
  ],
  "Speed Tweaks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1556062106"
  ],
  "[1.0] More Lamps - Vanilla Power Consumption Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1498059985"
  ],
  "[B18] Trading Economy Mod 2.4 ": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=TradingEconomy V2.4"
  ],
  "[RF] We're All Mad, Here! [b18]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=RF - We're All Mad Here"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
thank you for your contribution!
