### ISSUE TITLE
unknown mods found by m0bitz

### ISSUE THREAD

**Issue by m0bitz** [shakeyourbunny/RWMSDB#188]
{
 "meta": {
  "contributor": "m0bitz",
  "mods_known": 50,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Thu Jun  6 14:29:01 2019"
 },
 "unknown": {
  "Op Trait": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1660938830"
  ],
  "Project Itzal - Bonus Guns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1761548198"
  ],
  "Real Drug Names": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=784325872"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi, added your contribution, thank you.
