### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by LazyLizard95** [shakeyourbunny/RWMSDB#189]
{
 "meta": {
  "contributor": "",
  "mods_known": 28,
  "mods_unknown": 8,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Thu Jun  6 16:31:13 2019"
 },
 "unknown": {
  "EPOE Argonian Race Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=964937942"
  ],
  "EPOE Racc Race Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=940734267"
  ],
  "Lizardman": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1380836542"
  ],
  "Melanin Matters": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1680773158"
  ],
  "Mystery Meat": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1322984456"
  ],
  "Small Shelf": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1204763016"
  ],
  "Twitch Stories": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1575408914"
  ],
  "[B19] Small Shelf": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1435092881"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your contributions, these are not errors ;D
