### ISSUE TITLE
5 Unkown mods

### ISSUE THREAD

**Issue by NoLegs** [shakeyourbunny/RWMSDB#195]
{
 "meta": {
  "contributor": "",
  "mods_known": 64,
  "mods_unknown": 10,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Fri Jun  7 23:29:06 2019"
 },
 "unknown": {
  "Clutter Weapon Hands": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=ClutterMisc_Hands"
  ],
  "Craftable synthread and hyperweave": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=CraftableSynthreadAndHyperweave"
  ],
  "Psychology testing": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Psychology-master"
  ],
  "Raid Limiter": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=RaidLimiter"
  ],
  "Reduce eating without table debuff": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=REDUCE_eating_without_table_debuff_RW_1-0"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Please provide valid URLs for me to check out these mods. Thank you.
