### ISSUE TITLE
unknown mods found by Zyankali1995

### ISSUE THREAD

**Issue by zyankali1995** [shakeyourbunny/RWMSDB#196]
{
 "meta": {
  "contributor": "Zyankali1995",
  "mods_known": 168,
  "mods_unknown": 6,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Sun Jun  9 15:22:08 2019"
 },
 "unknown": {
  "Animal Armor: Vanilla": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1743423205"
  ],
  "Auto-Mortars": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1743740869"
  ],
  "Flags and Banners": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1564928794"
  ],
  "Halloween Special Edition": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=775578146"
  ],
  "Holiday Special Edition": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=813190996"
  ],
  "Slave Outfits Cosmetic [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1524646980"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
thank you for your contribution!
