### ISSUE TITLE
unknown mods found by Zyankali1995

### ISSUE THREAD

**Issue by zyankali1995** [shakeyourbunny/RWMSDB#199]
{
 "meta": {
  "contributor": "Zyankali1995",
  "mods_known": 173,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Mon Jun 10 15:45:16 2019"
 },
 "unknown": {
  "CyberNet": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1725545225"
  ],
  "GlitterNet": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1725544583"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hello,

already added to the last batch of additions.

Thank you!
