### ISSUE TITLE
"Why Can't I Craft Neutroamine?" is not known

### ISSUE THREAD

**Issue by tymestrike** [shakeyourbunny/RWMSDB#201]
This mod is not in the database, submitting file as per request of the script and to help others. I didn't encounter any problems with it at the bottom but I am not going to assume that no issues could arise.
[rwms_unknown_mods_20190610-1504.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3273961/rwms_unknown_mods_20190610-1504.json.txt)

**Comment by shakeyourbunny** [comment]
The whole point of the issue tracker and generating unknown file diffs is that anybody can contribute to the database for sorting. You are very welcome to report any new mods :)

Though there will be a total revamp of the database, every contribution will be carried over.

**Comment by shakeyourbunny** [comment]
Thank you for your contribution, added this mod.
