### ISSUE TITLE
unknown mods found by Nuclearmayhem

### ISSUE THREAD

**Issue by Nuclearmayhem** [shakeyourbunny/RWMSDB#218]
{
 "meta": {
  "contributor": "",
  "mods_known": 591,
  "mods_unknown": 74,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Fri Jun 14 20:10:48 2019"
 },
 "unknown": {
  "1.0 - ACP - More Floors Wool Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1766524688"
  ],
  "A Dog Said... Animal Prosthetics - No Category": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=A_Dog_Said_1.0_nocategories"
  ],
  "Add Elona Shoujo [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1500213859"
  ],
  "Beetle People": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1504654099"
  ],
  "Better Luciferium": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1763032629"
  ],
  "Black Labs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1539699568"
  ],
  "Black Labs ADS Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542610508"
  ],
  "Blood_n_Science patches": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=__LocalCopy_Blood_n_Science patches_(15-5)"
  ],
  "CPBeasties ADS Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=847031944"
  ],
  "Caravan Gear [Android Tiers Patch]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1764610352"
  ],
  "Centaurs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1576793761"
  ],
  "Creatures of Ki": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1726422863"
  ],
  "CuttingBoard": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1683074793"
  ],
  "Deer Extension": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1336473924"
  ],
  "Dryadic for Zhthy'hl patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1762470648"
  ],
  "Elite Archotech": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1744648077"
  ],
  "Elite Bionics Framework": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1665403571"
  ],
  "Glitter Tech Nanosuit Buff (B19)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1500339730"
  ],
  "Griffins for Rimworld": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1217424545"
  ],
  "Griffins for Rimworld + A Dog Said": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1217424702"
  ],
  "Hardcore Storytellers": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=831774478"
  ],
  "HealthDifferenceAuraCore": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544596991"
  ],
  "Hisa Faction": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1617772184"
  ],
  "I Don't Feel So Good": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1557912142"
  ],
  "Kijin - Rimmu-Nation Apparel Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1766355420"
  ],
  "Kijin - Spartan Foundry and Field Medic Apparel Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1769023905"
  ],
  "Kilhn Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1631597972"
  ],
  "LBE's Australian Wildlife": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=943062673"
  ],
  "Lamia(add animal)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1496720306"
  ],
  "MSE - Save Compatibility Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1754355771"
  ],
  "Misc Robots HP Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1755078568"
  ],
  "MoreCarpets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1214762492"
  ],
  "NPS Patches": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=NPS Patches"
  ],
  "NeotokyoMusic": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1764392883"
  ],
  "New Joy Source: Play Music": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1533909405"
  ],
  "No Pause Challenge": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1517419925"
  ],
  "No Weapon Looting": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1751392625"
  ],
  "Ookami": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1728391882"
  ],
  "Orassan RimAtomics Compatability": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1761396749"
  ],
  "Pack Elephants": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1731893652"
  ],
  "Patch for [T] MoreFloors + Vanilla Animals Expanded - Livestock": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1728650253"
  ],
  "Pre-Industrial Survivors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1576540921"
  ],
  "Real World Food": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1717902989"
  ],
  "RimFortress": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1386829954"
  ],
  "Rimcraft Allied Races": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1747686739"
  ],
  "Rimhammer - The End Times - Dwarfs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1758115494"
  ],
  "Sailor Scouts Hair [19]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Sailor Scouts Hair"
  ],
  "Silts Passive Cooler": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1510393058"
  ],
  "SparrowsMOD [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542481590"
  ],
  "Star Trek: Phasers": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1698954027"
  ],
  "Star Trek: Replicator": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1698953753"
  ],
  "Star Trek: Uniforms": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1698953487"
  ],
  "Super Mario Animals and Extras": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1551384389"
  ],
  "WA VG-Addon v1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1555643945"
  ],
  "WA v1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1548358607"
  ],
  "Warhammer: Zhthy'hl": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1754691148"
  ],
  "Yay Chocobos!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1664168224"
  ],
  "[1.0] A Dog Said Patch for SparrowsMOD": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542732624"
  ],
  "[1.0] DE Surgeries - Alpha Animals patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1732715130"
  ],
  "[1.0] Feed Box": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542404987"
  ],
  "[1.0] Hyena ADS Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544322252"
  ],
  "[1.0] SwimmingKit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542399915"
  ],
  "[1.0]Kan Colle hair style (Any) ": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1721089419"
  ],
  "[B19]GW-hair,face": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1347934694"
  ],
  "[JPT] Soft Warm Beds - No Hospitality": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1714753342"
  ],
  "[sd] round tables": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=761403726"
  ],
  "unofficial patch - Elite Bionic Framework + Archotech Expanded Prosthetics": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1746071278"
  ],
  "unofficial patch - Elite Bionic Framework + Callistans": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1746192199"
  ],
  "unofficial patch - Elite Bionic Framework + The Birds and The Bees": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1746407810"
  ],
  "\u3068\u3052\u306d\u305a\u307f\uff06\u30b7\u30ed": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1497068717"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Thank you for your contribution!
