### ISSUE TITLE
hello, more unknown mods (._.)/ 

### ISSUE THREAD

**Issue by sebitor** [shakeyourbunny/RWMSDB#221]
[rwms_unknown_mods_20190615-2110.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3293719/rwms_unknown_mods_20190615-2110.json.txt)

{
 "meta": {
  "contributor": "",
  "mods_known": 585,
  "mods_unknown": 7,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Sat Jun 15 21:10:57 2019"
 },
 "unknown": {
  "Desynchronized: Tales and News (v1.6.2)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1573233249"
  ],
  "JetPack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1761704409"
  ],
  "Kijin CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1768010561"
  ],
  "More Brains and Implants!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1766307828"
  ],
  "Nuclear Fire": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1652608513"
  ],
  "PlanCakes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1765790157"
  ],
  "Rimsenal - Federation + Combat Extended Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1769401413"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
thank you for your contribution!
