### ISSUE TITLE
Unknown Mod (Grazing Lands)

### ISSUE THREAD

**Issue by XenoXilus** [shakeyourbunny/RWMSDB#234]
{
 "meta": {
  "contributor": "",
  "mods_known": 2,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Fri Jun 21 19:24:19 2019"
 },
 "unknown": {
  "Grazing Lands": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1770268130"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Thank you, already added :)
