### ISSUE TITLE
unknown mods found by obncomputer@gmx.de

### ISSUE THREAD

**Issue by ewphoenix123** [shakeyourbunny/RWMSDB#235]
{
 "meta": {
  "contributor": "obncomputer",
  "mods_known": 97,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.6",
  "time": "Sat Jun 22 11:26:35 2019"
 },
 "unknown": {
  "ExtendedFabrics": [
   "not_categorized",
   ""
  ],
  "Sophotronics": [
   "not_categorized",
   ""
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your contribution
