### ISSUE TITLE
Unknown Mod: Hard version of [DE] Surgeries

### ISSUE THREAD

**Issue by kruemelkeksfan** [shakeyourbunny/RWMSDB#237]
{
 "meta": {
  "contributor": "",
  "mods_known": 44,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Sat Jun 22 19:05:42 2019"
 },
 "unknown": {
  "[1.0] DE Surgeries Hard": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1556888077"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your contribution, thank you!
