### ISSUE TITLE
unknown mod: Colorblind Minerals

### ISSUE THREAD

**Issue by Newkz** [shakeyourbunny/RWMSDB#238]
{
 "meta": {
  "contributor": "",
  "mods_known": 129,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Sun Jun 23 14:42:34 2019"
 },
 "unknown": {
  "Colorblind Minerals": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1424338139"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi, added your contribution.
