### ISSUE TITLE
Unknown Mods - 11

### ISSUE THREAD

**Issue by Espilonarge** [shakeyourbunny/RWMSDB#241]
{
 "meta": {
  "contributor": "",
  "mods_known": 184,
  "mods_unknown": 11,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Tue Jun 25 05:54:25 2019"
 },
 "unknown": {
  "JobsLimitTweak": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1266811081"
  ],
  "Peanuts (And Peanut Accessories)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1528059319"
  ],
  "Project Itzal - Autorifles": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1644400407"
  ],
  "Project Itzal - Launchers": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1648138523"
  ],
  "Project Itzal - Machine guns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1645700038"
  ],
  "Project Itzal - Pistols": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1643712123"
  ],
  "Project Itzal - Revolvers": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1643300295"
  ],
  "Project Itzal - SMGs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1643874257"
  ],
  "Project Itzal - Shotguns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1645152190"
  ],
  "Project Itzal - Snipers": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1644911837"
  ],
  "Warmer Power Armour": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1512534049"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
thank you for your contribution!
