### ISSUE TITLE
Unknown Mod

### ISSUE THREAD

**Issue by LemmysTash** [shakeyourbunny/RWMSDB#244]
{
 "meta": {
  "contributor": "",
  "mods_known": 80,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Wed Jun 26 19:13:12 2019"
 },
 "unknown": {
  "RIMMSAssemble": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1780241645"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Thank you, this mod was already added though.
