### ISSUE TITLE
unknown mods found by Sunnday3@gmail.com

### ISSUE THREAD

**Issue by AltcakeResident** [shakeyourbunny/RWMSDB#246]
{
 "meta": {
  "contributor": "Sunnday3",
  "mods_known": 3,
  "mods_unknown": 39,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Sat Jun 29 06:57:07 2019"
 },
 "unknown": {
  "Chunk-B-Gone": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1667031221"
  ],
  "Definitely More Cannons - No Armored Centipedes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1554666637"
  ],
  "Emergency Healer (nerfed)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1718133070"
  ],
  "F@#king Drop Pods": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1732988429"
  ],
  "Fallout Vault Structures & Floors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1111335237"
  ],
  "Faster Apparel": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1780328624"
  ],
  "Fix Bayonets!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1713017020"
  ],
  "HungerGuns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1773566320"
  ],
  "Kaiser Armory [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1768843436"
  ],
  "Kijin Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1730054284"
  ],
  "Moloy Traits": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1777036482"
  ],
  "Much Quieter Fallout Vault Doors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1516098507"
  ],
  "Muffalo Plants": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1557936382"
  ],
  "NR_AutoMachineTool [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1447829247"
  ],
  "Non-Flammable Metal (B19)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1259296818"
  ],
  "Nonuple rocket launcher": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1739385799"
  ],
  "Oni of the Rim - Faceless heads": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1732462355"
  ],
  "Outfit Builder": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1754037908"
  ],
  "Pain Scale Sanity": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1764900471"
  ],
  "Pawn Badge - Deutsches Heer": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1756882185"
  ],
  "Pawnmorpher": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1761365657"
  ],
  "RIMMSAssemble": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1780241645"
  ],
  "ROK ARMY MOD": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1606074406"
  ],
  "Raise The Roof 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1776143665"
  ],
  "Realistic Prosthetics Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1498483853"
  ],
  "Rimmunator - Weapons": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1613978906"
  ],
  "Rotmeth": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1780182516"
  ],
  "Simple Clones": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1553705431"
  ],
  "Stargate Races": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1665935468"
  ],
  "Start Fire with Wood Log": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1572632484"
  ],
  "Surgical Body Shaping (SBS)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1217321550"
  ],
  "The Complete Drug Overhaul": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1199169567"
  ],
  "The Great War": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=794159377"
  ],
  "Warframe M-A-V Pack[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1529582998"
  ],
  "Warframe [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1521727860"
  ],
  "Wave Survival": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1781679122"
  ],
  "[1.0] Nukes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1777069843"
  ],
  "[FIXED] GeneSeed": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1561468783"
  ],
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your contributions, thank you!
