### ISSUE TITLE
Unknown mod

### ISSUE THREAD

**Issue by TheMilso** [shakeyourbunny/RWMSDB#247]
{
 "meta": {
  "contributor": "",
  "mods_known": 27,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1722",
  "rwms_version": "0.94.6",
  "time": "Sat Jun 29 14:13:28 2019"
 },
 "unknown": {
  "Better Social Skills v1.1 [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1530263498"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Thank you, this mod should be already recognized by 0.94.7 without a database update.
