### ISSUE TITLE
April 25th

### ISSUE THREAD

**Issue by Halcyonix** [shakeyourbunny/RWMSDB#25]
{
 "Bulk Components": "not_categorized",
 "Glitterworld medicine craftable": "not_categorized",
 "Halo - Weapons [1.0]": "not_categorized",
 "Idle Power Consumption": "not_categorized",
 "Luciferium craftable": "not_categorized",
 "More Vanilla Turrets [1.0]": "not_categorized",
 "Nature is Beautiful v1.3 [1.0]": "not_categorized",
 "Power Beam have heat!": "not_categorized",
 "VGP Bulk Garden Drinks": "not_categorized",
 "VGP Garden Dyes": "not_categorized",
 "time": "Thu Apr 25 09:14:02 2019"
}

**Comment by shakeyourbunny** [comment]
Hello,

added your contribution, have fun!
