### ISSUE TITLE
Unknown Mod

### ISSUE THREAD

**Issue by Newkz** [shakeyourbunny/RWMSDB#252]
{
 "meta": {
  "contributor": "",
  "mods_known": 149,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Sun Jun 30 19:52:57 2019"
 },
 "unknown": {
  "Reich Armory Ausf\u00fchrung": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1778648673"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
thank you for your contribution!
