### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by JonasScheirs** [shakeyourbunny/RWMSDB#254]
{
 "meta": {
  "contributor": "",
  "mods_known": 230,
  "mods_unknown": 8,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Mon Jul  1 01:01:02 2019"
 },
 "unknown": {
  "Humanoid Project": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1785657108"
  ],
  "Hunting Squad": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1771088625"
  ],
  "Kijin Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1730054284"
  ],
  "Kijin: Apparello 2 Apparel Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1786755277"
  ],
  "Kijin: Rimmu-Nation Apparel Patch (converted for regular girl pawns)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1782342296"
  ],
  "RIMMSAssemble": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1780241645"
  ],
  "RazzleDazzle!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1778162471"
  ],
  "Reich Armory Ausf\u00fchrung": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1778648673"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
thank you for your contribution!
