### ISSUE TITLE
Unknown Mods (40)

### ISSUE THREAD

**Issue by Ashran31** [shakeyourbunny/RWMSDB#255]
[rwms_unknown_mods_20190701-1440.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3345605/rwms_unknown_mods_20190701-1440.json.txt)

I checked the script cause my game loaded broken today, and after some update of the script there are now some unknown mods, where before there were none

**Comment by shakeyourbunny** [comment]
strange, they all should be covered by 0.94.7 by now, there were no real new unknown ones in it.

but thank you for your effort, have fun playing RimWorld!
