### ISSUE TITLE
Unknown Mod

### ISSUE THREAD

**Issue by TheIvanic** [shakeyourbunny/RWMSDB#258]
Specifically Questionable Ethics Enhanced, but I'll link the file for completeness
[rwms_unknown_mods_20190702-1737.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3352419/rwms_unknown_mods_20190702-1737.json.txt)

**Comment by shakeyourbunny** [comment]
Hi, 

this mod was already added, but thank you!
