### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by LemmysTash** [shakeyourbunny/RWMSDB#265]
{
 "meta": {
  "contributor": "",
  "mods_known": 129,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Thu Jul  4 17:48:45 2019"
 },
 "unknown": {
  "Questionable Ethics Enhanced": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1787359789"
  ],
  "RIMMSAssemble": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1780241645"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hello,

thank you for your contribution, it's already in the database.
