### ISSUE TITLE
unknown mods found by stealthbob69

### ISSUE THREAD

**Issue by stealthbob69** [shakeyourbunny/RWMSDB#271]
{
 "meta": {
  "contributor": "stealthbob69",
  "mods_known": 301,
  "mods_unknown": 26,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Fri Jul  5 12:33:19 2019"
 },
 "unknown": {
  "Bob's Mass Effect Turians": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1783756827"
  ],
  "Buyable Quest Rewards": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1634468067"
  ],
  "Crystalloid (Rewrite) temporary fix": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1792132836"
  ],
  "Flommel: A Dog Said Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1509105839"
  ],
  "GOPNI VanillaHair Replace MOD": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1776097153"
  ],
  "Gerzee Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1783636077"
  ],
  "Gravel": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1613910454"
  ],
  "Helmets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1602890924"
  ],
  "Humanoid Project": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1785657108"
  ],
  "Indoctrination Virus": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1682888866"
  ],
  "Kijin Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1730054284"
  ],
  "Kijin: Apparello 2 Apparel Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1786755277"
  ],
  "Krysa Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Krysas_3.8 V1.0"
  ],
  "Modified Leeani": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1783359454"
  ],
  "Pain Scale Sanity": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1764900471"
  ],
  "Pawnmorpher": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1786466855"
  ],
  "Playable Kobolds": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=947429973"
  ],
  "Questionable Ethics Enhanced": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1787359789"
  ],
  "RIMMSAssemble": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1780241645"
  ],
  "RazzleDazzle!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1778162471"
  ],
  "RimJobWorld Extension": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=rjw-ex"
  ],
  "RimSlave: Daenerys' Army: A Game of Thrones Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1746084920"
  ],
  "Various hat modes!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1741002085"
  ],
  "Yet Another Stockpile Presets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1778592386"
  ],
  "[O21] Pokemon Rim": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1787773815"
  ],
  "\u725b\u3086\u304b\uff58\u30de\u30ad": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=\u725b\u3086\u304b\u30de\u30ad v1.0"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your contribution, thank you!
