### ISSUE TITLE
"Mass Cooking" and "Persistent Float Menus" are unknown

### ISSUE THREAD

**Issue by flangopink** [shakeyourbunny/RWMSDB#281]
{
 "meta": {
  "contributor": "",
  "mods_known": 247,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.7",
  "time": "Mon Jul  8 20:21:53 2019"
 },
 "unknown": {
  "Mass Cooking": [
   "not_categorized",
   ""
  ],
  "Persistent Float Menus": [
   "not_categorized",
   ""
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi,
these mods are already included in the latest updates!
