### ISSUE TITLE
unknown mods found by stealthbob69

### ISSUE THREAD

**Issue by stealthbob69** [shakeyourbunny/RWMSDB#282]
{
 "meta": {
  "contributor": "stealthbob69",
  "mods_known": 301,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Mon Jul  8 16:55:56 2019"
 },
 "unknown": {
  "Life Support": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1778018794"
  ],
  "\u725b\u3086\u304b\uff58\u30de\u30ad": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=\u725b\u3086\u304b\u30de\u30ad v1.0"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
please include a URL for review / categorizing, thank you!
