### ISSUE TITLE
Unknown Mods Dump (0.94.7) 14/07/19 16:16 BST

### ISSUE THREAD

**Issue by XenoXilus** [shakeyourbunny/RWMSDB#287]
{
 "meta": {
  "contributor": "",
  "mods_known": 168,
  "mods_unknown": 42,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Sun Jul 14 16:15:27 2019"
 },
 "unknown": {
  "Desynchronized: Tales and News (v1.6.2)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1573233249"
  ],
  "Door Mat R1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1505423207"
  ],
  "Hardworking animals 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=933324235"
  ],
  "Humanoid Alien Races 2.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=839005762"
  ],
  "Industrial Age - Objects and Furniture": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=777197241"
  ],
  "Invisible Conduits 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1551213814"
  ],
  "Meals Are Meals [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1574250341"
  ],
  "MineItAll - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1512765986"
  ],
  "More Furniture [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544944259"
  ],
  "More Slaves [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541360626"
  ],
  "More Trade Ships - Double Population": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1556125249"
  ],
  "More Vanilla Turrets - Turret Extensions Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1516356320"
  ],
  "More Vanilla Turrets 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1478936958"
  ],
  "Nature is Beautiful v1.4 [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1530259312"
  ],
  "Quarry 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1543177113"
  ],
  "RimWriter - Books, Scrolls, Tablets, and Libraries": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1521844535"
  ],
  "Roof Support 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1553179450"
  ],
  "SF [v1.0] Priority Treatment": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1502876618"
  ],
  "SF [v1.0] Rain Removes All Filth": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1502875716"
  ],
  "Sun Lights [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1530250702"
  ],
  "Vanilla Furniture Expanded - Medical Module": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613"
  ],
  "[1.0] Apparel Organizer": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1586143254"
  ],
  "[1.0] Combat Extended Guns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1582570547"
  ],
  "[1.0] Combat Extended: Shields": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1586351220"
  ],
  "[1.0] Material Filter": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541305730"
  ],
  "[1.0] Ratkin + Combat Extended Compatibility Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1739122102"
  ],
  "[B19]GW-HornHair": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1426084242"
  ],
  "[KV] Change Dresser - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1385697110"
  ],
  "[KV] Configurable Maps - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1507370392"
  ],
  "[KV] Faction Control - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1509102551"
  ],
  "[KV] Force Do Job - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180719500"
  ],
  "[KV] Keep Hands & Feet - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1528295006"
  ],
  "[KV] More Trait Slots - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1508292711"
  ],
  "[KV] Path Avoid - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180719857"
  ],
  "[KV] RimFridge - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235"
  ],
  "[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180718516"
  ],
  "[KV] Show Hair With Hats or Hide All Hats - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180826364"
  ],
  "[KV] Trading Spot - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180719658"
  ],
  "[RF] Advanced Bridges [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1539309348"
  ],
  "[RF] Realistic Planets [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1571623829"
  ],
  "[RF] Tribal Pawn Names [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1539314168"
  ],
  "ameiro anime hairs for 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1207934602"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi,

consider upgrading to 0.94.7, all of your unknown mods are detect by the update :-)

Have a nice day!
