### ISSUE TITLE
Load Order Recommendation/Correction

### ISSUE THREAD

**Issue by TrippyTheO** [shakeyourbunny/RWMSDB#295]
Just used RWMS to sort my mod list, says there are no unknown mods, super cool, (helps when I actually update RWMS I guess) but RWMS placed Carpenter Tables (relatively new mod) before Minify Everything, but Carpenter Tables says it should be placed after Minify Everything.

**Comment by shakeyourbunny** [comment]
Hi,
I modified the order that minify everything will be sorted before Carpenter Tables.
