### ISSUE TITLE
Unknown Mods by MatthewTh0, Mod Order Suggestion, and Can You Prevent Enabling All Unrecognized Mods (Even Disabled Ones)? (Edited 7/22/19)

### ISSUE THREAD

**Issue by MatthewTh0** [shakeyourbunny/RWMSDB#297]
{
 "meta": {
  "contributor": "MatthewTh0",
  "mods_known": 206,
  "mods_unknown": 9,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Wed Jul 17 20:21:41 2019"
 },
 "unknown": {
  "Eating without a table is a war crime": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1522719077"
  ],
  "Map Edit Tools": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1796223954"
  ],
  "More Mental Breaks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=837047494"
  ],
  "More Than Capable": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1803932954"
  ],
  "No Death Cooties On Armour": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=914638336"
  ],
  "Real Gun Names": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1258067475"
  ],
  "Realistic Power": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1502993704"
  ],
  "Star Wars Republic Equipment": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=826070389"
  ],
  "Xen's Storytellers: Raul Bison": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=908490348"
  ]
 },
 "version": 2
}

And yeah, it keeps enabling some mods I had disabled for some reason (tested multiple times to make sure). Also for full disclosure, I edited out a few mods from this list that were from previous versious that I just hadn't unsubscribed from yet (hoping they would be updated).

Edit: 
I figured out it just enables all unknown mods regardless of whether they were enabled or not which I find as weird thing. Would be cool to be fixed.

Also, I have some load order things. First, the person said that Startup Impact doesn't need to go above core which also removes warnings from Fluffy's Mod Manager if done so. This leads me to my second point which is that RimThemes does not work if loaded below Startup Impact (which means it needs to go near the top before Startup Impact) (I guess I would put them both as "load_first" assuming alphabetical order is what happens). Lastly, Programmable Vents causes an error if loaded before ReplaceStuff (could put ReplaceStuff in "production" maybe). This is an odd one to fix, I put Replace Stuff above Programmable Vents since it does add in game items (the in-wall coolers) despite mostly adding functionality.

Then I wanted to suggest categories for the above mods I listed (to help you a bit), in order: "annoyance", "biome", "ai", "skill", "annoyance", "patch", "energy", "combat"/"weapons"/ "combat addons" (adds weapon and armor), and "storyteller".  I also found more unknown mods (again edited) which I would suggest as "gameplay". "gameplay", "storyteller", and "structure"/"combat".

{
 "meta": {
  "contributor": "MatthewTh0",
  "mods_known": 189,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Mon Jul 22 20:39:27 2019"
 },
 "unknown": {
  "Common Ailments": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1798703154"
  ],
  "MSE: Real Organism": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1801108349"
  ],
  "RimOverhaul": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1760022158"
  ],
  "Very Ordinary Security Buildings": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1793655819"
  ],
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hello, will be correcting / adding things one by one.

**Comment by shakeyourbunny** [comment]
first set of unknown mods added.

**Comment by shakeyourbunny** [comment]
added second set of unknown mods.

btw you can replace the "not_categorized" entry with the correct ones if you like by yourself.

**Comment by shakeyourbunny** [comment]
fixes added:
 - moved startup impact down below core
 - moved replace stuff to gameplay

re-enabling disabled unknown mods is fixed in the next coming release (or use the github/source version).
