### ISSUE TITLE
Mod order suggestion

### ISSUE THREAD

**Issue by Taemaly** [shakeyourbunny/RWMSDB#303]
(if lowest are the one that overwrite higher ones) then Extended storage extended must be placed straight after extended storage, or otherwise it will give errors. Camera+ must be above TD enhancement pack to prevent errors. Birds and bees RBSE edition has to be under DE surgeries for RBSE (to prevent animal infertility problem) but also higher than Animalcollab proj patch to prevent another error.

**Comment by aboleba** [comment]
Seconding that Camera+ needs to be before TD Enhancement Pack.

**Comment by shakeyourbunny** [comment]
Hi!

fixed: Extended Storage (Extended)
already fixed: Camera+ + TD enhancement pack
fixed (hopefully): birds and the bees RBSE edition + DE surgeries
