### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by Taemaly** [shakeyourbunny/RWMSDB#304]
{
 "meta": {
  "contributor": "",
  "mods_known": 437,
  "mods_unknown": 7,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Fri Jul 19 21:20:58 2019"
 ,
 "unknown": {
  "Biomes! 2: Caves": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1275333892"
  ],
  "Biomes! 2: Core": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1288714774"
  ],
  "Desynchronized: Tales and News (.1)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1573233249"
  ],
  "MSE: Real Organism": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1801108349"
  ],
 "unknown": {
  "'[Ods] Mens Hair' Facial Stuff Patch": [
   "not_categorized",
   https://steamcommunity.com/sharedfiles/filedetails/?id=1806095722"
 ],
    "Faster Smoothing": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1807439023"
  ],
  "Infused Filter (Auto Seller Filter)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1807842939"
  ],
 "version": 2

**Comment by shakeyourbunny** [comment]
your JSON is borked.. can you provide the correctly formatted please? thank you!
