### ISSUE TITLE
unknown mods found by Dhandspikerwade

### ISSUE THREAD

**Issue by DHandspikerWade** [shakeyourbunny/RWMSDB#309]
{
 "meta": {
  "contributor": "handspiker2",
  "mods_known": 85,
  "mods_unknown": 1,
  "os": "linux",
  "rimworld_version": "1.0.2282 rev730",
  "rwms_version": "0.94.7",
  "time": "Sun Jul 21 15:05:09 2019"
 },
 "unknown": {
  "[CP] Portable Nerfed Generator": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1503021433"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your contribution, thank you!
