### ISSUE TITLE
unknown mods 4/25

### ISSUE THREAD

**Issue by BlackGoatPC** [shakeyourbunny/RWMSDB#31]
[rwms_unknown_mods_20190425-1317.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3118164/rwms_unknown_mods_20190425-1317.json.txt)

**Comment by shakeyourbunny** [comment]
Can you provide a URL for the mod "Mines"? I could not locate it, is this "[1.0] Mines" (seems to look like a mining hut building mod)?

**Comment by BlackGoatPC** [comment]
that's it yeah https://steamcommunity.com/sharedfiles/filedetails/?id=1545681321

**Comment by shakeyourbunny** [comment]
Thank you for your contribution, btw the syb is my nick on steam ;D
