### ISSUE TITLE
Unknown mods - Combat Extended Fixes (1776175645)

### ISSUE THREAD

**Issue by TwistedMinds2** [shakeyourbunny/RWMSDB#312]
{
 "meta": {
  "contributor": "",
  "mods_known": 126,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Mon Jul 22 12:34:19 2019"
 },
 "unknown": {
  "Combat Extended Fixes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1776175645"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your contribution, thank you!
