### ISSUE TITLE
Unknown mods found by Taranchuk (+34 mods)

### ISSUE THREAD

**Issue by Taranchuk** [shakeyourbunny/RWMSDB#314]
{
 "meta": {
  "contributor": "",
  "mods_known": 76,
  "mods_unknown": 34,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev722",
  "rwms_version": "0.94.7",
  "time": "Wed Jul 24 15:20:32 2019"
 },
 "unknown": {
  "Advanced Parka Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1677752791"
  ],
  "Alien Vs Predator Combat Extended Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1773036608"
  ],
  "Animal Barn and Feeding Trough": [
   "not_categorized",
   "https://ludeon.com/forums/index.php?topic=25580.0"
  ],
  "Annoying Life": [
   "not_categorized",
   "https://steamcommunity.com/workshop/filedetails/?id=1439886892"
  ],
  "Biosphere Core": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1807370855"
  ],
  "Brain Implants and More (implants)": [
   "not_categorized",
   "https://steamcommunity.com/workshop/filedetails/?l=russian&id=1807318209"
  ],
  "Clothes To Cloths": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1756871084"
  ],
  "Craftable Drugs + Glit med": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Craftable Drugs +Glit Med"
  ],
  "EPOE + DE Surgery Bone Fix": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=836916859"
  ],
  "Equip Gas Masks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1713214833"
  ],
  "Go explore!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1814100216"
  ],
  "Infectious Creatures": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1430501911"
  ],
  "Misc Turrets CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Misc Turrets CE Patch"
  ],
  "MyPatchesForRimworld": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=MyPatches"
  ],
  "OHU Addon: C-77 Freighter": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=OHU C-77 Freighter"
  ],
  "OHU Addon: S-342 Transporter": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=OHU S-342 Transport"
  ],
  "Remote Doors": [
   "not_categorized",
   "https://github.com/TGPArcher/RemoteDoors/releases/latest"
  ],
  "RimGacha": [
   "not_categorized",
   "https://github.com/Lanilor/RimGacha"
  ],
  "Seasonal Weather": [
   "not_categorized",
   "https://github.com/AaronCRobinson/SeasonalWeather"
  ],
  "Smoke Grenades(Reloaded)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=942616945"
  ],
  "Space Worms": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1078857582"
  ],
  "Vanilla Raid Strategies Unknown": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1783482279"
  ],
  "Various Space Ship Chunk (Continued)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1158568885"
  ],
  "[CP] I Need Nourishment!: Malnutrition Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=I Need Nourishment! - Malnutrition Patch (1.0)"
  ],
  "[CP] Rimmu-Nation: Proper Shotguns Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Rimmu-Nation - Proper Shotguns Patch (1.0)"
  ],
  "[XND] Adrenaline!": [
   "not_categorized",
   "https://github.com/XeoNovaDan/Adrenaline/releases"
  ],
  "[XND] Nocturnal Animals": [
   "not_categorized",
   "https://github.com/XeoNovaDan/NocturnalAnimals/releases"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
can you provide some links where I can check out these mods? thank you!

**Comment by Taranchuk** [comment]
Here are some links that I found in the About.xml files. 
https://github.com/AaronCRobinson/SeasonalWeather
https://github.com/Lanilor/RimGacha
https://github.com/notfood/RimWorld-MoreThanCapable
https://github.com/TGPArcher/RemoteDoors/releases/latest
https://github.com/XeoNovaDan/Adrenaline/releases
https://github.com/XeoNovaDan/NocturnalAnimals/releases
https://steamcommunity.com/sharedfiles/filedetails/?id=1814100216
If you need something more specific, let me know.

**Comment by shakeyourbunny** [comment]
No, these links are sufficient for me, thank you!

Will integrate these mods.

**Comment by Taranchuk** [comment]
There are still 27 mods, but I do not know which of them have already been added to the database, and which ones are not. If you could provide the names of mods that are not yet in the database, then I could search for them in the history of the browser or in Google.

**Comment by shakeyourbunny** [comment]
I edited in the submission all the provided links and removed already known mods from it.

**Comment by Taranchuk** [comment]
Advanced Parka Mod - https://steamcommunity.com/sharedfiles/filedetails/?id=1677752791
Alien Vs Predator Combat Extended Patch - https://steamcommunity.com/sharedfiles/filedetails/?id=1773036608
Annoying Life - https://steamcommunity.com/workshop/filedetails/?id=1439886892
Biosphere Core - https://steamcommunity.com/sharedfiles/filedetails/?id=1807370855&searchtext=
Brain Implants and More (implants) - https://steamcommunity.com/workshop/filedetails/?l=russian&id=1807318209
Clothes To Cloths - https://steamcommunity.com/sharedfiles/filedetails/?id=1756871084
EPOE + DE Surgery Bone Fix - https://steamcommunity.com/sharedfiles/filedetails/?l=russian&id=836916859
Equip Gas Masks - https://steamcommunity.com/sharedfiles/filedetails/?id=1713214833&searchtext=
Infectious Creatures - https://steamcommunity.com/sharedfiles/filedetails/?id=1430501911
Smoke Grenades(Reloaded) - https://steamcommunity.com/sharedfiles/filedetails/?id=942616945
Space Worms - https://steamcommunity.com/sharedfiles/filedetails/?id=1078857582
Vanilla Raid Strategies Unknown - https://steamcommunity.com/sharedfiles/filedetails/?id=1783482279
Various Space Ship Chunk (Continued) - https://steamcommunity.com/sharedfiles/filedetails/?id=1158568885

for OHU addons I can’t remember where I downloaded them, but they are addons for Orbital Hubs United mod https://ludeon.com/forums/index.php?topic=31906.0 mod

Also, the mod Smoke Grenades(Reloaded) is update for the mod https://steamcommunity.com/sharedfiles/filedetails/?id=942616945, but I can’t remember where I downloaded the update

And the mod 'Animal Barn and Feeding Trough' is the heir to these mods, but I also can’t remember where I downloaded it https://ludeon.com/forums/index.php?topic=25580.0

**Comment by shakeyourbunny** [comment]
thank you, added your mods. have fun!
