### ISSUE TITLE
Unknown Mods 4/26

### ISSUE THREAD

**Issue by Kyonai** [shakeyourbunny/RWMSDB#32]
[rwms_unknown_mods_20190426-0556.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3120762/rwms_unknown_mods_20190426-0556.json.txt)

**Comment by Kyonai** [comment]
Auto Caravan Equip: https://github.com/SupesSolutions/RWAutoCaravanEquip

HolyWasher: https://rim-world.com/holy-washer-mod/

Inspiration: https://ludeon.com/forums/index.php?topic=29871.0

Noku Mushrooms: https://ludeon.com/forums/index.php?topic=46210.0

Remove eating without table debuff: https://ludeon.com/forums/index.php?topic=47962.0

ZARS Tribal Reborn: https://rim-world.com/tribal-essentials-mod/

**Comment by shakeyourbunny** [comment]
Hello, thank you for your efforts. btw the Auto Caravan Equip mod is very neat ;-)

have fun!
