### ISSUE TITLE
RIMMSLoadUp before core

### ISSUE THREAD

**Issue by capitanjal** [shakeyourbunny/RWMSDB#327]
https://steamcommunity.com/sharedfiles/filedetails/?id=1686660152
RIMMSLoadUp is put before core

**Comment by lbmaian** [comment]
FYI, that mod is outdated now.

**Comment by capitanjal** [comment]
omfg i will not notice it if you didn't say it..., there is not a chance you add that like a feature disable obsolete mods, there is a few
