### ISSUE TITLE
unknown mods found by Bdan720

### ISSUE THREAD

**Issue by Bdan720** [shakeyourbunny/RWMSDB#33]
{
 "Avali Race Mod - 1.4.0": "not_categorized",
 "Dubs Break Mod": "not_categorized",
 "USCM - Turret 1.0": "not_categorized",
 "USCM - Xenomorphs Faction 1.0": "not_categorized",
 "Yabils: Space Gremlins": "not_categorized",
 "[1.0] Xenite Industries": "not_categorized",
 "_contributor": "Bdan720",
 "time": "Fri Apr 26 13:37:26 2019",
 "\u5996\u602a\u67511.2": "not_categorized"
}

**Comment by shakeyourbunny** [comment]
I guess the "\u5996\u602a\u67511.2" is "妖怪村1.2" on https://steamcommunity.com/sharedfiles/filedetails/?id=1532938687

added your mods, thank you!
