### ISSUE TITLE
unknown mods found by Wolfehart

### ISSUE THREAD

**Issue by Wolfehart** [shakeyourbunny/RWMSDB#330]
{
 "meta": {
  "contributor": "khaiming89",
  "mods_known": 109,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Tue Jul 30 11:38:14 2019"
 },
 "unknown": {
  "Cybernetic Warfare": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1811369911"
  ],
  "Vanilla Apparel Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817"
  ],
  "Vanilla Armour Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282"
  ],
  "Vanilla Weapons Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your mods.
