### ISSUE TITLE
unknown mods found by sceiler

### ISSUE THREAD

**Issue by sceiler** [shakeyourbunny/RWMSDB#338]
{
 "meta": {
  "contributor": "",
  "mods_known": 64,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.9",
  "time": "Wed Jul 31 20:53:11 2019"
 },
 "unknown": {
  "Better Sun Lamps": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1728222820"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added the mod.
