### ISSUE TITLE
Animal Variety Coats and Better Infestation compatibility issue

### ISSUE THREAD

**Issue by lbmaian** [shakeyourbunny/RWMSDB#341]
Better Infestations (https://steamcommunity.com/sharedfiles/filedetails/?id=1319614331) must be loaded after Animal Variety Coats (https://steamcommunity.com/sharedfiles/filedetails/?id=1511926373), or else XML errors will be logged.

From Better Infestations description: "This mod will patch add thingclass to all the vanilla bugs. Other mods such as Animal Variety Coats do this too, make sure Better Infestations loads after them."

Animal Variety Coats is currently categorized as "texture", but it's not only texture replacement; it also does XML patching for vanilla bugs. Better Infestations is categorized as "animal", and it does provide new XML defs, but also does XML patching for vanilla bugs.

**Comment by shakeyourbunny** [comment]
I'll look into it.

**Comment by shakeyourbunny** [comment]
I moved Animal Variety Coats above Better Infestations, should do the trick now.
