### ISSUE TITLE
Unknown mods found by KaijinZero

### ISSUE THREAD

**Issue by KaijinZero** [shakeyourbunny/RWMSDB#342]
{
 "meta": {
  "contributor": "",
  "mods_known": 73,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Sat Aug  3 19:25:24 2019"
 },
 "unknown": {
  "Easy Kibble": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=820970594"
  ],
  "Vanilla Animals Expanded \u2014 Cats and Dogs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1823540489"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added both mods.

please let me know if there are any problems with A Dog Said and Vanilla Animals Expanded. If so, please re-open the issue and let me know.
