### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by Sazra** [shakeyourbunny/RWMSDB#348]
{
 "meta": {
  "contributor": "",
  "mods_known": 115,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Sun Aug  4 14:50:02 2019"
 },
 "unknown": {
  "Carry Capacity Fix": [
   "not_categorized",
   "https://ludeon.com/forums/index.php?topic=47837.msg451757#msg451757"
  ],
  "Magical Menagerie": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1821617793"
  ]
 },
 "version": 2
}

The mod carry capacity fix is a mod from the ludeon forums.

**Comment by shakeyourbunny** [comment]
I edited in the correct URL for Carry Capacity fix.

added both mods.
