### ISSUE TITLE
unknown mods found by lanzljo@outlook.de

### ISSUE THREAD

**Issue by SeppDE** [shakeyourbunny/RWMSDB#349]
{
 "meta": {
  "contributor": "lanzljo",
  "mods_known": 369,
  "mods_unknown": 6,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Sun Aug  4 15:13:17 2019"
 },
 "unknown": {
  "Advanced Munitions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1693437813"
  ],
  "Compound Bow": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1553445852"
  ],
  "Large Outpost": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1571943277"
  ],
  "Niche Tactical Weapons": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1738466411"
  ],
  "Soaking Wet is a Good Thing": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1636419760"
  ],
  "TC Turret No Barrel Replace": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1620727219"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your mods, btw there is an update to rwms available.

**Comment by SeppDE** [comment]
Update isn't working on my system cause of https://github.com/shakeyourbunny/RWMS/issues/29 but thanks.
