### ISSUE TITLE
unknown mods found by arokidaaron93@gmail.com

### ISSUE THREAD

**Issue by Shinudesu** [shakeyourbunny/RWMSDB#350]
{
 "meta": {
  "contributor": "arokidaaron93",
  "mods_known": 94,
  "mods_unknown": 23,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Sun Aug  4 22:19:09 2019"
 },
 "unknown": {
  "Cargo Pod Transport[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1536615776"
  ],
  "DontBlockDoorMod[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1691076769"
  ],
  "Door Mat R1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1505423207"
  ],
  "Facial Stuff 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=818322128"
  ],
  "Humanoid Alien Races 2.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=839005762"
  ],
  "Lord of the Rims - Dwarves": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1400238872"
  ],
  "Lord of the Rims - Elves": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1400234784"
  ],
  "Lord of the Rims - Hobbits": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1400227853"
  ],
  "Lord of the Rims - The Third Age": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1400245220"
  ],
  "MarsX v3 - Musky Edition": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=732754899"
  ],
  "More Furniture [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544944259"
  ],
  "Quarry 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1543177113"
  ],
  "Realistic Darkness 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1531882210"
  ],
  "Rim of Madness - Bones": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180573408"
  ],
  "Rimfire 2.5": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Rimfire 2.5"
  ],
  "Simple Slavery[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1635565299"
  ],
  "Vanilla Furniture Expanded - Medical Module": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613"
  ],
  "[1.0] Android tiers": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1386412863"
  ],
  "[1.0] Combat Extended Guns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1582570547"
  ],
  "[1.0] RPG Style Inventory": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1561221991"
  ],
  "[KV] RimFridge - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235"
  ],
  "[KV] Show Hair With Hats or Hide All Hats - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180826364"
  ],
  "[KV] Trading Spot - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180719658"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Please upgrade to the current build of RWMS (0.98.9), then all your mods will be detected.
https://github.com/shakeyourbunny/RWMS/releases
