### ISSUE TITLE
Unknown mod list by Dessometrics

### ISSUE THREAD

**Issue by Victaria90** [shakeyourbunny/RWMSDB#36]
"All for One [1.0]": "not_categorized",
 "Boulder Trap Mod": "not_categorized",
 "Call of Cthulhu - Elder Things Tweak": "not_categorized",
 "Children and Pregnancy - v0.5a": "not_categorized",
 "Clear The Stockpiles": "not_categorized",
 "ClutterDoors": "not_categorized",
 "Combat Extended Guns Retextured": "not_categorized",
 "Compact Benches": "not_categorized",
 "Cyber Fauna 1.0": "not_categorized",
 "Designator Shapes": "not_categorized",
 "Dinosauria Unoffical CE Patch": "not_categorized",
 "Dubs Skylights Glass+Lights Patch": "not_categorized",
 "ETRT: Cannibal Tweaks": "not_categorized",
 "Extended Storage RimCuisine Patch": "not_categorized",
 "Extra Traits for CE": "not_categorized",
 "Fire Warden": "not_categorized",
 "Fishing Nets": "not_categorized",
 "Frontline - Bunkers CE Version": "not_categorized",
 "Frontline - Trenches CE Version": "not_categorized",
 "Fueled Smelter": "not_categorized",
 "Generic CE Ammo": "not_categorized",
 "Genetic Rim Dinosauria CE Patch": "not_categorized",
 "Gimmicks": "not_categorized",
 "Hardcore Fertile Fields": "not_categorized",
 "Harvest Sync": "not_categorized",
 "Improved Infestation": "not_categorized",
 "LOTR and Bones": "not_categorized",
 "Lighter Colorful Traits": "not_categorized",
 "Lizardmen Lite": "not_categorized",
 "Medieval Bones": "not_categorized",
 "Medieval Times Balance Patch (CE version)": "not_categorized",
 "Megafauna (CE compatibility patch)": "not_categorized",
 "Mercer's Backpacks (B19)": "not_categorized",
 "MizuModAddon\u3010ZP\u3011RCC\u30101.0\u3011": "not_categorized",
 "Muh Eggs! [1.0]": "not_categorized",
 "NightVision": "not_categorized",
 "Optimization: CE Ammo": "not_categorized",
 "Optimization: Meats": "not_categorized",
 "Ore processing": "not_categorized",
 "Pawns Paint! Restored": "not_categorized",
 "RPG Style Inventory CE Patch": "not_categorized",
 "RS Horse Armor and Saddles for Animal Gear": "not_categorized",
 "RS Patch for RimFace (Facial Stuff Version)": "not_categorized",
 "RePower EPOE Patch": "not_categorized",
 "RePower HighTech Laboratory Facilities Patch": "not_categorized",
 "RePower Rimatomics Patch": "not_categorized",
 "RimFace for Facial Stuff 1.0": "not_categorized",
 "Rimsenal + Combat Extended Compatibility Patch": "not_categorized",
 "SeedsPleaseAddon\u3010ZP\u3011RCC\u30101.0\u3011": "not_categorized",
 "Sparkling Worlds - CE Patch [1.0] - Combat Extendend Compatibility": "not_categorized",
 "Tiny Workbenchs": "not_categorized",
 "To My Side! - Medieval": "not_categorized",
 "Toggle Refuelable": "not_categorized",
 "Toolmetric CE Patch": "not_categorized",
 "Uninstall Rimworld": "not_categorized",
 "[SYR] Neuter": "not_categorized",
 "_contributor": "",
 "time": "Fri Apr 26 20:49:34 2019",
 "\u3010ZP\u3011Japanese bread": "not_categorized",
 "\u3010ZP\u3011Rice cultivating civilization\u30101.0\u3011": "not_categorized"

I tried to help categorize them
{
 "All for One [1.0]": "gameplay",
 "Boulder Trap Mod": "combat",
 "Call of Cthulhu - Elder Things Tweak": "patch",
 "Children and Pregnancy - v0.5a": "gameplay",
ai "ClutterDoors": "furniture",
 "Combat Extended Guns Retextured": "texture",
 "Compact Benches": "production",
 "Cyber Fauna 1.0": "gameplay",
 "Designator Shapes": "ui",
 "Dinosauria Unoffical CE Patch": "patch",
 "Dubs Skylights Glass+Lights Patch": "patch",
 "ETRT: Cannibal Tweaks": "ai",
 "Extended Storage RimCuisine Patch": "patch",
 "Extra Traits for CE": "patch",
 "Fire Warden": "ai",
 "Fishing Nets": "food",
 "Frontline - Bunkers CE Version": "combat",
 "Frontline - Trenches CE Version": "combat",
 "Fueled Smelter": "production",
 "Generic CE Ammo": "patch",
 "Genetic Rim Dinosauria CE Patch": "patch",
 "Gimmicks": "item",
 "Hardcore Fertile Fields": "patch",
 "Harvest Sync": "gameplay",
 "Improved Infestation": "gameplay",
 "LOTR and Bones": "patch",
 "Lighter Colorful Traits": "skill",
 "Lizardmen Lite": "race",
 "Medieval Bones": "patch",
 "Medieval Times Balance Patch (CE version)": "patch",
 "Megafauna (CE compatibility patch)": "patch",
 "Mercer's Backpacks (B19)": "clothing",
 "MizuModAddon\u3010ZP\u3011RCC\u30101.0\u3011": "patch",
 "Muh Eggs! [1.0]": "annoyance",
 "NightVision": "skill",
 "Optimization: CE Ammo": "annoyance",
 "Optimization: Meats": "annoyance",
 "Ore processing": "production",
 "Pawns Paint! Restored": "joy",
 "RPG Style Inventory CE Patch": "patch",
 "RS Horse Armor and Saddles for Animal Gear": "clothing",
 "RS Patch for RimFace (Facial Stuff Version)": "patch",
 "RePower EPOE Patch": "patch",
 "RePower HighTech Laboratory Facilities Patch": "patch",
 "RePower Rimatomics Patch": "patch",
 "RimFace for Facial Stuff 1.0": "patch",
 "Rimsenal + Combat Extended Compatibility Patch": "patch",
 "SeedsPleaseAddon\u3010ZP\u3011RCC\u30101.0\u3011": "patch",
 "Sparkling Worlds - CE Patch [1.0] - Combat Extendend Compatibility": "patch",
 "Tiny Workbenchs": "production",
 "To My Side! - Medieval": "gameplay",
 "Toggle Refuelable": "ui",
 "Toolmetric CE Patch": "patch",
 "Trading Spot": "ui",
 "Uninstall Rimworld": "patch",
 "[SYR] Neuter": "medicine",
 "_contributor": "",
 "time": "Fri Apr 26 20:08:17 2019",
 "\u3010ZP\u3011Japanese bread": "food",
 "\u3010ZP\u3011Rice cultivating civilization\u30101.0\u3011": "production"
}

**Comment by shakeyourbunny** [comment]
Hello,

thank you for your contribution. Your pre-categorization helped me sped up the processing a lot.

Thank you!

**Comment by Victaria90** [comment]
Awesome I'm happy it actually helped. If you see any that I may have gotten wrong let me know. I mod A LOT so i will probably do this for every list i have.

**Comment by shakeyourbunny** [comment]
Well, I always welcome new unknown mods and if something it's already pre-categorized, the better ;)
