### ISSUE TITLE
Unknown mods found by SimplySublimee

### ISSUE THREAD

**Issue by SimplySublimee** [shakeyourbunny/RWMSDB#360]
{
 "meta": {
  "contributor": "",
  "mods_known": 164,
  "mods_unknown": 8,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.9",
  "time": "Wed Aug  7 00:05:33 2019"
 },
 "unknown": {
  "More Planning (Russian translation)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1551276794"
  ],
  "RimGacha": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1804047115"
  ],
  "Wall Sun Lamp": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1825653111"
  ],
  "[Azur Lane] Bataan": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1824632058"
  ],
  "[SimplySublime]: Bok Choy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1316807919"
  ],
  "[WD] Expanded Floors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1817862464"
  ],
  "[WD] Expanded Floors (Dropdown Menu Addon)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1817883612"
  ],
  "[XND] Adrenaline!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1823138604"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your mods ;D
