### ISSUE TITLE
unknown mods found by wolfehart

### ISSUE THREAD

**Issue by Wolfehart** [shakeyourbunny/RWMSDB#366]
{
 "meta": {
  "contributor": "wolfehart",
  "mods_known": 114,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Wed Aug  7 23:44:49 2019"
 },
 "unknown": {
  "Armor Core": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1826918547"
  ],
  "Self reloading traps": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1820959221"
  ],
  "Stop the spam": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1825943530"
  ],
  "Try to find it!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1825952633"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your mods.
