### ISSUE TITLE
unknown mods found

### ISSUE THREAD

**Issue by Soxiel** [shakeyourbunny/RWMSDB#367]
{
 "meta": {
  "contributor": "",
  "mods_known": 142,
  "mods_unknown": 46,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Wed Aug  7 19:57:59 2019"
 },
 "unknown": {
  "Corners for 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1822319961"
  ],
  "Desynchronized: Tales and News (v1.7.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1573233249"
  ],
  "Facial Stuff 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=818322128"
  ],
  "Field Medic [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541287769"
  ],
  "Geth": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1819987395"
  ],
  "Gloomy Extra - Kitchen": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1730938407"
  ],
  "Harvest Organs Post Mortem - 4.1 [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1204502413"
  ],
  "Horses (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1233906319"
  ],
  "Humanoid Alien Races 2.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=839005762"
  ],
  "Let's Trade! [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541261044"
  ],
  "More Vanilla Turrets - Turret Extensions Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1516356320"
  ],
  "More Vanilla Turrets 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1478936958"
  ],
  "Quarry 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1543177113"
  ],
  "RimEffect - Asari of the Rims": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1204011879"
  ],
  "Rimsenal - Storyteller pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=725952322"
  ],
  "Roof Support 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1553179450"
  ],
  "Roppoi hair 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1100547661"
  ],
  "SF [v1.0] Priority Treatment": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1502876618"
  ],
  "Small Comms Console [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1530281472"
  ],
  "Sparkling Worlds - Full Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922"
  ],
  "Stackable Chunks [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1619558325"
  ],
  "Star Wars - Factions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=918227266"
  ],
  "Star Wars - Fully Functional Lightsabers": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=918200645"
  ],
  "Star Wars - The Force": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=918226861"
  ],
  "Tilled Soil (Rebalanced) - 120%": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1727629447"
  ],
  "Vanilla Furniture Expanded - Medical Module": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613"
  ],
  "Veinminer R1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541978411"
  ],
  "Wandering Caravans [v2.4.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1171600778"
  ],
  "While You're Up [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544626521"
  ],
  "[1.0] Android tiers": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1386412863"
  ],
  "[1.0] RPG Style Inventory": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1561221991"
  ],
  "[CP] Chicken Mitchell - Hairstyles (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541531035"
  ],
  "[CP] Detailed Body Textures II (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1501435493"
  ],
  "[CP] Prisoner Outfit (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1507216525"
  ],
  "[CP] Red Horse Furniture (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541528454"
  ],
  "[CP] Rimmu-Nation - Clothing (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541536041"
  ],
  "[CP] Rimmu-Nation - Weapons (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1608498683"
  ],
  "[KV] Change Dresser - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1385697110"
  ],
  "[KV] Change Mirror - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1390088618"
  ],
  "[KV] In-Game Definition Editor - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1568772413"
  ],
  "[KV] More Trait Slots - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1508292711"
  ],
  "[KV] RimFridge - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235"
  ],
  "[KV] Trading Spot - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1180719658"
  ],
  "[RF] Pawns are Capable! [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1539312975"
  ],
  "[RF] Realistic Planets [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1571623829"
  ],
  "[v1.0]-LinkableDoors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1498129268"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi,

please upgrade your RWMS to the most current version on https://github.com/shakeyourbunny/RWMS/releases.

Thank you.

I only discovered 1 unknown mod, Geth, which I added.
