### ISSUE TITLE
Unrecognized Mod - Vanilla Animals Expanded: Patch Pack (1824112352)

### ISSUE THREAD

**Issue by TwistedMinds2** [shakeyourbunny/RWMSDB#368]
{
 "meta": {
  "contributor": "",
  "mods_known": 130,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.9",
  "time": "Wed Aug  7 18:07:20 2019"
 },
 "unknown": {
  "Vanilla Animals Expanded: Patch Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1824112352"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added, thank you.
