### ISSUE TITLE
Unknown Mod: ZARS Tribalism

### ISSUE THREAD

**Issue by Saphrym** [shakeyourbunny/RWMSDB#370]
"unknown": {
  "ZARS Tribalism": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1820484592"
  ]
 },

**Comment by shakeyourbunny** [comment]
please add the full JSON instead of a "sanitized" one.

As I archive every contribution, I need  to have the meta information in a machine-readable format in order to properly credit you in the future if I have to rebuild the database anew.

Thank you.
