### ISSUE TITLE
unknown mods found by mjlogg21

### ISSUE THREAD

**Issue by mjlogg21** [shakeyourbunny/RWMSDB#371]
{
 "meta": {
  "contributor": "mjlogg21",
  "mods_known": 148,
  "mods_unknown": 13,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.9",
  "time": "Fri Aug  9 02:58:32 2019"
 },
 "unknown": {
  "Animals Are Fun": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\Animals Are Fun"
  ],
  "Apex: Rimworld Legends test": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\ApexRimworldLegends"
  ],
  "Balut": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\Balut"
  ],
  "Change map edge limit: Dev Build": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\ChangeMapEdge-master"
  ],
  "Compare Tool": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\CompareTool"
  ],
  "Corpse To Fuel x15": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\1760614672 Corpse To Fuel x15"
  ],
  "Lord of the Rims: Men and Beasts": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\Lord-of-the-Rims---Men-and-Beasts-master"
  ],
  "NamesGalore": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\NamesGalore-master"
  ],
  "Oats!": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\1803357494 Oats!"
  ],
  "Remove Rocket Launchers": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\1511597470 Remove Rocket Launchers"
  ],
  "Rescued Pawns Will Ask": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\Rescued Pawns Will Ask"
  ],
  "Tier 2 Temperature": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\1798787901 Tier 2 Temperature"
  ],
  "[K]Extra Stone": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\852103845 [K]Extra Stone"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
duplicate if #372
