### ISSUE TITLE
unknown mods

### ISSUE THREAD

**Issue by Daedalus2788** [shakeyourbunny/RWMSDB#377]
{
 "meta": {
  "contributor": "",
  "mods_known": 409,
  "mods_unknown": 10,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.9",
  "time": "Mon Aug 12 03:39:59 2019"
 },
 "unknown": {
  "Eccentric Tech: Foxy's Armory": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1828175049"
  ],
  "JJ fixes RimEffect: Weapons and Armor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1590397542"
  ],
  "Old Gods: Terrain": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1503447998"
  ],
  "Reich Armory": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1778648673"
  ],
  "Rimscavenger Kit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1795206570"
  ],
  "Shiba Wanko: A Dog Said Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1569572667"
  ],
  "Simple Search Bar in Filter": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1827546987"
  ],
  "Simple Turrets: TE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1798616048"
  ],
  "Wall Mounted Turrets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1812077718"
  ],
  "Xeva Faction -XFB with Vanilla Body Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1823554014"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
