### ISSUE TITLE
Got some unknown mods

### ISSUE THREAD

**Issue by transbiod** [shakeyourbunny/RWMSDB#38]
[rwms_unknown_mods_20190427-2247.json.txt](https://github.com/shakeyourbunny/RWMS/files/3124366/rwms_unknown_mods_20190427-2247.json.txt)

**Comment by shakeyourbunny** [comment]
Hello,

thank you for your contribution, have fun playing!

**Comment by transbiod** [comment]
Thank you so much for your awesome work
