### ISSUE TITLE
Unknwon mods found by Mlie

### ISSUE THREAD

**Issue by emipa606** [shakeyourbunny/RWMSDB#382]
[rwms_unknown_mods_20190813-2058.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3498435/rwms_unknown_mods_20190813-2058.json.txt)

* Chased Spacer: New mod that adds chased spacer-event, no dependencies
* Christmas Stuff (continued): Local mod, work in progress, can be ignored
* Forbid Blueprints: Makes blueprints allow/forbiddable, no dependencies
* Insulation: New mod that adds insulation-properties to materials, no dependencies
* Mechanoid Nerf for Combat Extended: Lowers attributes for mechanoids when using combat extended, should be loaded after CE
* Mercenaries For Me: Lets you hire mercenaries, no dependencies
* Needs Comms (Continued): Stops chased-events if no powered com-station exists, no dependencies
* RePower Android Tiers Patch: RePower Patch for Android Tiers, should be loaded after  RePower, JecsTools, Humanoid Alien Races 2.0, [1.0] Android tiers
* RePower Electric Stonecutting Table Patch: RePower Patch for Electric Stonecutting Table, should be loaded after RePower and Electric Stonecutting Table
* RePower GloomyFurniture Patch: RePower Patch for GloomyFurniture, should be loaded after RePower and GloomyFurniture
* RePower RT's Weapon Pack Patch: RePower Patch for RT's Weapon Pack, should be loaded after RePower and RT's Weapon Pack (normal or CE-edition)
* RePower UN-Colony Patch: RePower Patch for UN-Colony, should be loaded after RePower and UN-Colony
* Vanilla Animals Expanded: Patch Pack: Some patches for Vanilla Animals Extended, loaded after A Dog Said... Animal Prosthetics, [1.0] Combat Extended, Vanilla Animals Expanded — Cats and Dogs, Vanilla Animals Expanded — Livestock, Vanilla Animals Expanded
* [O21] Anti-Infestation Thumper: Stops infestations if powered, no dependencies

**Comment by shakeyourbunny** [comment]
added your stuff, keep up the good work!
