### ISSUE TITLE
Some new Unknown mods

### ISSUE THREAD

**Issue by transbiod** [shakeyourbunny/RWMSDB#385]
{
 "meta": {
  "contributor": "",
  "mods_known": 284,
  "mods_unknown": 11,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.9",
  "time": "Wed Aug 14 16:29:04 2019"
 },
 "unknown": {
  "Fast Spreading Grass (Reload)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1821131780"
  ],
  "MSE: Prosthetic Combat": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1826357503"
  ],
  "Prosthetic Combat Framework": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1826357123"
  ],
  "RePower Android Tiers Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1829651604"
  ],
  "RePower Electric Stonecutting Table Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1829654591"
  ],
  "RimCuisine 2 Core": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833592062"
  ],
  "RimCuisine 2 Meals and Munchies Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833592940"
  ],
  "RimCuisine 2: Bottling and Brewing Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833592532"
  ],
  "RimCuisine 2: Smokes and Shrooms Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833593222"
  ],
  "Simple Search Bar in Filter": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1827546987"
  ],
  "Verb Expansion Framework": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1819780093"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
uuhuh so many interesting mods..  thank you for your contribution!
