### ISSUE TITLE
unknown mods

### ISSUE THREAD

**Issue by ElvisUntot** [shakeyourbunny/RWMSDB#386]
{
 "meta": {
  "contributor": "",
  "mods_known": 128,
  "mods_unknown": 5,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Wed Aug 14 22:06:09 2019"
 },
 "unknown": {
  "Heppoko Security Turrets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1501229518"
  ],
  "Insulation": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1832114425"
  ],
  "Personal Defense System": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1553674506"
  ],
  "Silts Reworked Starting Techs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1510432778"
  ],
  "Wall Mounted Turrets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1812077718"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added :--)
