### ISSUE TITLE
Unknown Mods found by Taemaly

### ISSUE THREAD

**Issue by Taemaly** [shakeyourbunny/RWMSDB#387]
{
 "meta": {
  "contributor": "",
  "mods_known": 435,
  "mods_unknown": 6,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Thu Aug 15 12:25:46 2019"
  "Additional Joy Objects Lite": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1602579533"
  ],
  "Better Sunlamps & More": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1814882699"
  ],
  "Biomes! 2: Caves": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1275333892"
  ],
  "Biomes! 2: Core": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1288714774"
  
  ],
  "[O21] Anti-Infestation Thumper": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1831016992"
  ],
  "[O21] WikiRim": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1834856478"
 
 "version": 2

**Comment by shakeyourbunny** [comment]
added
