### ISSUE TITLE
unknown mods found

### ISSUE THREAD

**Issue by Treazul** [shakeyourbunny/RWMSDB#388]
{
 "meta": {
  "contributor": "",
  "mods_known": 120,
  "mods_unknown": 1,
  "os": "linux",
  "rimworld_version": "1.0.2282 rev730",
  "rwms_version": "0.94.9",
  "time": "Fri Aug 16 11:59:31 2019"
 },
 "unknown": {
  "Additional Joy Objects Lite": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1602579533"
  ]
 },
 "version": 2
}

**Comment by Treazul** [comment]
Additionally it cannot find information on "Deep Rim" ( https://ludeon.com/forums/index.php?topic=39262.0 ) but that mod has a bunch of meta data issues anyway

**Comment by shakeyourbunny** [comment]
already added :)
