### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by SeppDE** [shakeyourbunny/RWMSDB#390]
{
 "meta": {
  "contributor": "",
  "mods_known": 285,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Sat Aug 17 12:41:10 2019"
 },
 "unknown": {
  "Additional Joy Objects Lite": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1602579533"
  ],
  "Simple Search Bar in Filter": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1827546987"
  ],
  "[CP] Rimmu-Nation: Gloves N' Boots": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836963709"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
