### ISSUE TITLE
More Unknown mods!!

### ISSUE THREAD

**Issue by Zaken187** [shakeyourbunny/RWMSDB#391]
[rwms_unknown_mods_20190817-2302.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3512718/rwms_unknown_mods_20190817-2302.json.txt)

These are all extremely new, save for TY Male Body and Oni of the Rim CE Patch..

RIMMLoadup needs to be placed before not after Core. Throws errors otherwise.

Also for the following mods:

Individuality, More Practical Traits, People can Change, More Trait Slots.

The order must be:
People Can Change
Individuality
More Practical Traits
More Trait Slots

Otherwise, an Error is thrown out.

**Comment by shakeyourbunny** [comment]
added your mods :D
