### ISSUE TITLE
unknown mods found by sbrandsborg

### ISSUE THREAD

**Issue by sbrandsborg** [shakeyourbunny/RWMSDB#404]
{
 "meta": {
  "contributor": "sbrandsborg",
  "mods_known": 130,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Tue Aug 20 19:43:07 2019"
 },
 "unknown": {
  "Rejuvenate surgery": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1390755364"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added the mod, thank you.
