### ISSUE TITLE
Unknown mod found by dnecro

### ISSUE THREAD

**Issue by dnecro** [shakeyourbunny/RWMSDB#405]
{
 "meta": {
  "contributor": "",
  "mods_known": 75,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Mon Aug 19 00:06:31 2019"
 },
 "unknown": {
  "Medicine Kit Crafting": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=736582979"
  ],
  "Simple Cultivation": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=932333113"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added 2 mods, thank you
