### ISSUE TITLE
unknown modlist

### ISSUE THREAD

**Issue by KaijinZero** [shakeyourbunny/RWMSDB#407]
{
 "meta": {
  "contributor": "",
  "mods_known": 95,
  "mods_unknown": 6,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Tue Aug 20 15:44:35 2019"
 },
 "unknown": {
  "Map Wide Orbital Trade Beacon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1839069104"
  ],
  "No Barrack Penalty Buff": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1477038573"
  ],
  "Rabbie The Moonrabbit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1837246563"
  ],
  "RimCuisine 2: All Plants All Biomes Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1839071307"
  ],
  "RimCuisine 2: Bottling and Booze Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833592532"
  ],
  "Vanilla Animals Expanded \u2014 Arid Shrubland": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added.
