### ISSUE TITLE
Unknown mods found by Ridesdragons

### ISSUE THREAD

**Issue by ridesdragons** [shakeyourbunny/RWMSDB#411]
{
 "meta": {
  "contributor": "",
  "mods_known": 135,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Tue Aug 20 22:46:41 2019"
 },
 "unknown": {
  "Kura's Extra Gems": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1339121712"
  ],
  "Vanilla Furniture Expanded: Spacer Module": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836382920"
  ],
  "[K]Extra Stone": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=852103845"
  ]
 },
 "version": 2
}

**Comment by ridesdragons** [comment]
also, a note on current sorting: Survival Tools is currently set above Expanded Woodworking for VGP. This needs to be the other way around, fluffy's modloader will scream at you if you don't. I also had it spit "duplicate parts" errors, though this may be from a different incompatibility that was fixed by moving survival tools down in my list.

also, Cargo Pod Transport triggers a "null ThingClass" and "ThingClass is not ThingsWithComps" error in its current position. moving it up above rimatomics cleared the error, though I'm unsure exactly which mod was causing the issue.

here's my current modlist with the two mods moved to proper locations
[ModsConfig.txt](https://github.com/shakeyourbunny/RWMSDB/files/3523899/ModsConfig.txt)

**Comment by shakeyourbunny** [comment]
- added you mods.
- did a (hacky) reorganisation of Expanded Woodworking VGP + Survival Tools, hope this helps.
- moved CargoPod Transport above RimAtomics

thank you for your fix suggestions!
