### ISSUE TITLE
Unknown mods found by SimplySublimee

### ISSUE THREAD

**Issue by SimplySublimee** [shakeyourbunny/RWMSDB#412]
{
 "meta": {
  "contributor": "",
  "mods_known": 247,
  "mods_unknown": 11,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.9",
  "time": "Wed Aug 21 01:05:38 2019"
 },
 "unknown": {
  "CucumPear's Storytellers": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=893502233"
  ],
  "Endless Space 2 OST": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836287718"
  ],
  "Farmable Neutroamine_zh": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1821695119"
  ],
  "JukeBox": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1562235741"
  ],
  "Mutsuki Face": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1798348824"
  ],
  "Rabbie The Moonrabbit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1837246563"
  ],
  "RimCuisine 2: Bottling and Booze Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833592532"
  ],
  "RimCuisine 2: NERFED Drugs and Drinks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1837808298"
  ],
  "Simple Search Bar": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1827546987"
  ],
  "Sort colonist bar": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1826294989"
  ],
  "TY Female Faces and Hairs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1350568027"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
