### ISSUE TITLE
unknown mods found by ninekoki@gmail.com

### ISSUE THREAD

**Issue by ninekoki** [shakeyourbunny/RWMSDB#414]
{
 "meta": {
  "contributor": "ninekoki",
  "mods_known": 245,
  "mods_unknown": 5,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Wed Aug 21 21:27:57 2019"
 },
 "unknown": {
  "Cat's Crying Sound Reduction Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1633702129"
  ],
  "Girls' frontline Weapon Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1835440813"
  ],
  "Stony campfire": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1367897185"
  ],
  "Vanilla Animals Expanded \u2014 Arid Shrubland": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626"
  ],
  "[FGO]\u827e\u857e\u4ec0\u57fa\u4f3d\u52d2\u670d\u88c5/Ereshkigal Apparel Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1763236543"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
