### ISSUE TITLE
Dependency mix-up: CyberNet loading before GlitterNet

### ISSUE THREAD

**Issue by Zholf** [shakeyourbunny/RWMSDB#416]
"CyberNet" (https://steamcommunity.com/sharedfiles/filedetails/?id=1725545225) is sorted before one of its required items "GlitterNet" (https://steamcommunity.com/workshop/filedetails/?id=1725544583), which results in an inability to create a new world.

**Comment by shakeyourbunny** [comment]
fixed sort order.
