### ISSUE TITLE
unknown mods found

### ISSUE THREAD

**Issue by MattRobinson41** [shakeyourbunny/RWMSDB#417]
{
 "meta": {
  "contributor": "",
  "mods_known": 116,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Wed Aug 21 21:54:36 2019"
 },
 "unknown": {
  "Alpha Biomes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1841354677"
  ],
  "Vanilla Animals Expanded \u2014 Arid Shrubland": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626"
  ],
  "Vanilla Furniture Expanded: Spacer Module": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836382920"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
