### ISSUE TITLE
Unknows mods found by Mlie

### ISSUE THREAD

**Issue by emipa606** [shakeyourbunny/RWMSDB#423]
[rwms_unknown_mods_20190823-0937.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3533317/rwms_unknown_mods_20190823-0937.json.txt)

* Android tiers: Gynoids - Should be loaded after JecsTools, Humanoid Alien Races 2.0, [1.0] Android tiers
* Fire Warden CE Fix - Should be loaded after Fire Extinguisher, Fire Warden and [1.0] Combat Extended
* RePower Ceramics Patch - Should be loaded after [1.0]RePower and [1.0]Ceramics
* RePower Patch Pack - Should be loaded last, updates with support for new mods regularly and needs to be placed after [1.0]RePower and all mods it supports
* RePower Project RimFactory Patch - Should be loaded after [1.0]RePower, ProjectRimFactory-Core, ProjectRimFactory3.0-PublicBeta
* RePower Rimmu-Nation Patch - Should be loaded after [1.0]RePower, [CP]Rimmu-Nation-Clothing(1.0), [CP]Rimmu-Nation-Weapons(1.0), [CP]Rimmu-Nation-GlovesN'Boots(1.0)
* Vanilla Animals Expanded - Arid Shrubland - No dependencies
* Vanilla Furniture Expanded: Spacer Module - No dependencies

**Comment by shakeyourbunny** [comment]
added
