### ISSUE TITLE
Surely others have them already ;)

### ISSUE THREAD

**Issue by ElvisUntot** [shakeyourbunny/RWMSDB#426]
{
 "meta": {
  "contributor": "",
  "mods_known": 131,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Fri Aug 23 22:10:43 2019"
 },
 "unknown": {
  "Mud": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1841948997"
  ],
  "The God Launcher": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1636945257"
  ],
  "Underground Soil": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1840852546"
  ],
  "Vanilla Animals Expanded \u2014 Arid Shrubland": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
no, they were all unknown until know. :)
