### ISSUE TITLE
unknown mods found by Sunnday3@gmail.com

### ISSUE THREAD

**Issue by AltcakeResident** [shakeyourbunny/RWMSDB#427]
{
 "meta": {
  "contributor": "Sunnday3",
  "mods_known": 409,
  "mods_unknown": 10,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Fri Aug 23 16:34:06 2019"
 },
 "unknown": {
  "Drug Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1315731596"
  ],
  "Escape The Rimworld: Vanilla Weapons Reskinned": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1808015908"
  ],
  "Ground Turret Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1827776743"
  ],
  "More drugs mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1227842111"
  ],
  "Project Itzal: Extra Guns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1837340352"
  ],
  "RimCuisine 2: All Plants All Biomes Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1839071307"
  ],
  "RimCuisine 2: Bottling and Booze Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833592532"
  ],
  "Vanilla Animals Expanded \u2014 Arid Shrubland": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626"
  ],
  "Vanilla Furniture Expanded: Spacer Module": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1836382920"
  ],
  "[CP] DOOM": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1843130386"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
