### ISSUE TITLE
unknown mods found by MlTHRlL

### ISSUE THREAD

**Issue by Hoijima** [shakeyourbunny/RWMSDB#434]
{
 "meta": {
  "contributor": "",
  "mods_known": 184,
  "mods_unknown": 6,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sun Aug 25 15:22:10 2019"
 },
 "unknown": {
  "Kane's Jukebox": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1497113878"
  ],
  "Kenshi Hiver Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1840737944"
  ],
  "Kenshi Shek Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1844308802"
  ],
  "Kenshi Skeleton Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1841876651"
  ],
  "Make-AntigrainWarhead(\u53cd\u7c92\u5b50\u795e\u6559-\u5185\u7f6e\u4e2d\u6587)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1562376170"
  ],
  "Proximity": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1719896867"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
