### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by NKSHV** [shakeyourbunny/RWMSDB#437]
{
 "meta": {
  "contributor": "",
  "mods_known": 2,
  "mods_unknown": 40,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Mon Aug 26 12:30:53 2019"
 },
 "unknown": {
  "A Cornucopia of Unicorns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1788976612"
  ],
  "Age Reversing Mech Serum": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1826684801"
  ],
  "Always Allow Infestation": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1844683373"
  ],
  "Brain Implants and More (implants)!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1766307828"
  ],
  "Combat Tweaked": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1608299826"
  ],
  "Creatures of Goshen": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1823420608"
  ],
  "Crickets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1244830572"
  ],
  "CryptoCurrency Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1581141732"
  ],
  "Dragon Ball Z: Rimworld Adventures: Revived!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1811852071"
  ],
  "Evt Floors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1792420593"
  ],
  "Fat Cat": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1426171179"
  ],
  "Frieza Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1801849116"
  ],
  "Giraffes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1805833884"
  ],
  "Kenshi Hiver Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1840737944"
  ],
  "Kenshi Shek Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1844308802"
  ],
  "Kenshi Skeleton Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1841876651"
  ],
  "Large Faction Bases": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1841553735"
  ],
  "Luciferium+": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1496003776"
  ],
  "Mammoths": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1660248164"
  ],
  "Mental Shield Crystal": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1842983803"
  ],
  "Muffalant Genetic Rim Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1838114456"
  ],
  "No Shadows": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1780338926"
  ],
  "No Water Ripples": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1682760689"
  ],
  "Paint Bugs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1526632977"
  ],
  "RaidCaller\u53ec\u5524\u88ad\u51fb": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1418771791"
  ],
  "Resource Generators": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1583893207"
  ],
  "Resource Muffaloes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1818042854"
  ],
  "SRTS": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833992261"
  ],
  "SRTS Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1845423808"
  ],
  "Super random Self reloading traps": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1824624464"
  ],
  "Swords": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1845180112"
  ],
  "Take My Organs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1707966478"
  ],
  "Utility Weapons": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1809809821"
  ],
  "Vanilla Furniture Expanded: Security": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007"
  ],
  "Wake-up X": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1819639144"
  ],
  "Weird Defences": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1753026389"
  ],
  "Wildlife": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1778625372"
  ],
  "[XND] Skill Overhead": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1204378444"
  ],
  "\u9664\u53bb\u6b96\u6c11\u8005\u5de5\u4f5c\u9650\u5236 No work restrictions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1705132878"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
