### ISSUE TITLE
unknown mods found by danieltufton@gmail.com

### ISSUE THREAD

**Issue by flarefluffsune** [shakeyourbunny/RWMSDB#439]
{
 "meta": {
  "contributor": "danieltufton",
  "mods_known": 175,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Mon Aug 26 12:49:06 2019"
 },
 "unknown": {
  "More Thrumbos": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1789924054"
  ],
  "Palm Cats": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1807872961"
  ],
  "Teshi ADS Patch": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\ADS_patch_CoKi"
  ],
  "Vanilla Furniture Expanded: Security": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
