### ISSUE TITLE
Repower Reborn unknown mod

### ISSUE THREAD

**Issue by mkire** [shakeyourbunny/RWMSDB#446]
Repower Reborn is an updated fork of Repower. it can be put in the same load order as Repower can
 "unknown": {
  "RePowerReborn": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1845531445"
  ],

**Comment by shakeyourbunny** [comment]
I added the mod, but if you want a proper contribution credit, please provide the full dump.
This is needed to carry it over if any major database overhauls are made (at least one is planned).
