### ISSUE TITLE
Unknow_mods

### ISSUE THREAD

**Issue by czarneski77** [shakeyourbunny/RWMSDB#450]
[rwms_unknown_mods_20190829-2257.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3557928/rwms_unknown_mods_20190829-2257.json.txt)

**Comment by normous** [comment]
Vanilla Furniture Expanded: Security for me as well.

**Comment by shakeyourbunny** [comment]
added, there are some really interesting ones
