### ISSUE TITLE
More unknown mods

### ISSUE THREAD

**Issue by Taemaly** [shakeyourbunny/RWMSDB#451]
{
 "meta": {
  "contributor": "",
  "mods_known": 435,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Sat Aug 31 10:04:28 2019"
 },
 "unknown": {
  "Invisible Hats": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=853819518"
  ],
  "RimOverhaul: Without Ore and Gas System": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1842923420"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
