### ISSUE TITLE
Unknown Mod

### ISSUE THREAD

**Issue by hbpateiv** [shakeyourbunny/RWMSDB#452]
{
 "meta": {
  "contributor": "",
  "mods_known": 103,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sat Aug 31 13:27:47 2019"
 },
 "unknown": {
  "Plant Kibble": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1485048270"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
