### ISSUE TITLE
Unknown mods (Gwen's Gone Mental Traits + Wearing Armor Info)

### ISSUE THREAD

**Issue by TwistedMinds2** [shakeyourbunny/RWMSDB#455]
{
 "meta": {
  "contributor": "",
  "mods_known": 146,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sat Aug 31 17:59:39 2019"
 },
 "unknown": {
  "Gwen's Gone Mental Traits": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1848518121"
  ],
  "Wearing Armor Info": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1839305669"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
