### ISSUE TITLE
QualityBuilder

### ISSUE THREAD

**Issue by ElvisUntot** [shakeyourbunny/RWMSDB#458]
The mod is positioned at the very end of the list but the correct position seems to be at the beginning of the list (otherwise it is not working for me)

https://steamcommunity.com/sharedfiles/filedetails/?id=754637870

**Comment by ElvisUntot** [comment]
Same seems to be true with 'Simple Stockpile Presets'

https://steamcommunity.com/sharedfiles/filedetails/?id=1428628928

**Comment by shakeyourbunny** [comment]
Strange, but I am using both mods too and I don't experience any problems.

Care to share your mod list?

**Comment by ElvisUntot** [comment]
I will gladly share my list, but it will take a few days since I am on
vacation.

**Comment by ElvisUntot** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
  <version>1.0.2282 rev726</version>
  <activeMods>
    <li>Core</li>
    <li>818773962</li>
    <li>932008009</li>
    <li>839005762</li>
    <li>1336991209</li>
    <li>872762753</li>
    <li>1742245843</li>
    <li>1201382956</li>
    <li>1781679122</li>
    <li>1787359789</li>
    <li>1386412863</li>
    <li>1767214408</li>
    <li>836308268</li>
    <li>1550854139</li>
    <li>1123043922</li>
    <li>1372003680</li>
    <li>725956940</li>
    <li>1113137502</li>
    <li>815039373</li>
    <li>1539311991</li>
    <li>725576127</li>
    <li>1725544583</li>
    <li>753498552</li>
    <li>732569232</li>
    <li>1185265132</li>
    <li>1552146295</li>
    <li>1775170117</li>
    <li>1338280929</li>
    <li>1507370392</li>
    <li>1185281838</li>
    <li>1647782348</li>
    <li>882126182</li>
    <li>1180573408</li>
    <li>1545872070</li>
    <li>725747149</li>
    <li>1192504741</li>
    <li>1185307686</li>
    <li>1185276569</li>
    <li>1185269798</li>
    <li>1621766001</li>
    <li>974398773</li>
    <li>1543177113</li>
    <li>1496570408</li>
    <li>1833163132</li>
    <li>1552418917</li>
    <li>722085442</li>
    <li>769201959</li>
    <li>1447372624</li>
    <li>1505423207</li>
    <li>777197241</li>
    <li>1544944259</li>
    <li>833899765</li>
    <li>1750069106</li>
    <li>1321849735</li>
    <li>1127530465</li>
    <li>728314182</li>
    <li>1548975671</li>
    <li>1778018794</li>
    <li>1185274792</li>
    <li>1715402900</li>
    <li>1749316830</li>
    <li>1244299809</li>
    <li>1185278809</li>
    <li>1185906628</li>
    <li>1188485723</li>
    <li>1526599749</li>
    <li>1521844535</li>
    <li>1761704409</li>
    <li>745193823</li>
    <li>1569056149</li>
    <li>1588408365</li>
    <li>1508292711</li>
    <li>1621571024</li>
    <li>1209071221</li>
    <li>717575199</li>
    <li>1546666445</li>
    <li>1356838246</li>
    <li>1547394294</li>
    <li>1279012058</li>
    <li>1552507180</li>
    <li>1076950211</li>
    <li>1544626521</li>
    <li>724602224</li>
    <li>747645520</li>
    <li>1136958577</li>
    <li>950475543</li>
    <li>1204051019</li>
    <li>1098354593</li>
    <li>1688004964</li>
    <li>1501459305</li>
    <li>1828462622</li>
    <li>1478936958</li>
    <li>1552894416</li>
    <li>1556177629</li>
    <li>1604892474</li>
    <li>1628211313</li>
    <li>1723379043</li>
    <li>1501229518</li>
    <li>1553674506</li>
    <li>1812077718</li>
    <li>1369828656</li>
    <li>1301120711</li>
    <li>1541261044</li>
    <li>1180719658</li>
    <li>764375772</li>
    <li>765890823</li>
    <li>1611200179</li>
    <li>1454024362</li>
    <li>1295107035</li>
    <li>944669553</li>
    <li>1357090976</li>
    <li>826366050</li>
    <li>754637870</li>
    <li>1428628928</li>
    <li>1507748539</li>
    <li>1446523594</li>
    <li>1508850027</li>
    <li>1499848654</li>
    <li>1687566130</li>
    <li>1742151109</li>
    <li>761421485</li>
    <li>1739749298</li>
    <li>715565262</li>
    <li>1501832876</li>
    <li>947972722</li>
    <li>1509278793</li>
    <li>1516158345</li>
    <li>1568772413</li>
    <li>1706669545</li>
    <li>715565817</li>
    <li>1414302321</li>
    <li>1095331978</li>
    <li>1266570759</li>
    <li>1355637255</li>
    <li>1561221991</li>
    <li>1551734715</li>
    <li>725219116</li>
    <li>1339135272</li>
    <li>735106432</li>
  </activeMods>
</ModsConfigData>

**Comment by shakeyourbunny** [comment]
Sorry, but cannot reproduce the problem ;(
