### ISSUE TITLE
unknown mods found by AleksiMK

### ISSUE THREAD

**Issue by AleksiMK** [shakeyourbunny/RWMSDB#477]
{
 "meta": {
  "contributor": "AleksiMK",
  "mods_known": 229,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sat Sep  7 12:08:22 2019"
 },
 "unknown": {
  "Brain In a Jar Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1850955716"
  ],
  "Vanilla Factions Expanded: Core": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1854607105"
  ],
  "Vanilla Factions Expanded: Medieval": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1854610483"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
