### ISSUE TITLE
Vanilla Factions Expanded - Medieval

### ISSUE THREAD

**Issue by SpookieWookie** [shakeyourbunny/RWMSDB#493]
Hey just a small note, this needs bumped down to load after Rimcuisine 2 Core and Rimcuisine 2 Bottling and Booze - or it throws patching errors.

![image](https://user-images.githubusercontent.com/29523103/64494809-4d417a00-d289-11e9-9e8d-74584b07a344.png)
![image](https://user-images.githubusercontent.com/29523103/64494821-5fbbb380-d289-11e9-86cc-de4b623708bb.png)

**Comment by shakeyourbunny** [comment]
moved factions down to faction, sorry my fault. should work now.
