### ISSUE TITLE
unknown mods found

### ISSUE THREAD

**Issue by Treazul** [shakeyourbunny/RWMSDB#497]
{
 "meta": {
  "contributor": "",
  "mods_known": 133,
  "mods_unknown": 2,
  "os": "linux",
  "rimworld_version": "1.0.2282 rev730",
  "rwms_version": "0.95.1",
  "time": "Mon Sep  9 13:53:53 2019"
 },
 "unknown": {
  "Slither Race: Eye Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1839889476"
  ],
  "Supreme Melee": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1841138974"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
