### ISSUE TITLE
unknown mods found by Ranaark

### ISSUE THREAD

**Issue by Ranaark** [shakeyourbunny/RWMSDB#502]
{
 "meta": {
  "contributor": "",
  "mods_known": 106,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Tue Sep 10 12:25:08 2019"
 },
 "unknown": {
  "Metals Trader": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1855069167"
  ],
  "Planetary Drill": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1800616407"
  ],
  "Supreme Melee": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1841138974"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added missing mods, thank you!
