### ISSUE TITLE
unknown mods found by kd8lvt

### ISSUE THREAD

**Issue by kd8lvt** [shakeyourbunny/RWMSDB#504]
{
 "meta": {
  "contributor": "kd8lvt",
  "mods_known": 178,
  "mods_unknown": 5,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Wed Sep 11 15:32:08 2019"
 },
 "unknown": {
  "Deep Stack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1857927951"
  ],
  "Flak Dusters": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1843482822"
  ],
  "KilledEnemyAutoAllowed": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1858219355"
  ],
  "Metal Ain't Flammable: Vanilla": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1849248412"
  ]
 },
 "version": 2
}

**Comment by kd8lvt** [comment]
Deep Stack: Changes stack sizes for most items to 1,000
Flak Dusters: Adds Dusters with built-in Flak armor
KilledEnemyAutoAllowed: As the name suggests, auto-allows killed enemies.
Metal Ain't Flammable: Vanilla: As the name suggests, makes all metals inflammable.
MsCarsonelle Theme: An older theme for Rimworld. It's not specified as 1.0 compatible, but it is.

**Comment by shakeyourbunny** [comment]
added missing mods, thank you!
