### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by jupiterlily** [shakeyourbunny/RWMSDB#51]
[rwms_unknown_mods_20190502-2324.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3140166/rwms_unknown_mods_20190502-2324.json.txt)

**Comment by jupiterlily** [comment]
{
 "AnimalCollabProj Lite": "not_categorized",
 "Carcinoma spreads": "not_categorized",
 "Children and Pregnancy - Cheran": "not_categorized",
 "Deafness and Blindness": "not_categorized",
 "Flagstone Cheaper (3 per) V1.0": "not_categorized",
 "Meat Blend 0.19": "not_categorized",
 "More Luxury Stones": "not_categorized",
 "Plastic Revolution": "not_categorized",
 "Prepare For Combat": "not_categorized",
 "Scheduled Events": "not_categorized",
 "Slightly More Realistic Wool Production": "not_categorized",
 "Tamped Dirt Floor": "not_categorized",
 "[1.0] Baby muffalo is Muffalump": "not_categorized",
 "[1.0]-StockpileForDisaster": "not_categorized",
 "_contributor": "",
 "time": "Thu May  2 23:14:59 2019"
}

**Comment by shakeyourbunny** [comment]
Hello,

I added your mods to the database. thank you!
