### ISSUE TITLE
unknown mods found by whitmadm@gmail.com

### ISSUE THREAD

**Issue by davidwhitman** [shakeyourbunny/RWMSDB#52]
{
 "Wild Pok\u00e9mon [1.0]": "not_categorized",
 "[FSF] Improved Ship Reactors": "not_categorized",
 "_contributor": "whitmadm@gmail.com",
 "time": "Thu May  2 19:01:55 2019"
}

**Comment by davidwhitman** [comment]
{
 "Wild Pok\u00e9mon [1.0]": "not_categorized",
 "[FSF] Improved Ship Reactors": "not_categorized",
 "_contributor": "whitmadm@gmail.com",
 "time": "Thu May  2 19:01:55 2019"
}

**Comment by shakeyourbunny** [comment]
Hello,

I added these mods to the database. Thank you!

**Comment by davidwhitman** [comment]
Thanks for maintaining this tool! It's awesome.
