### ISSUE TITLE
unknown mods found by Supa3939Spider

### ISSUE THREAD

**Issue by Supa39Spider** [shakeyourbunny/RWMSDB#526]
{
 "meta": {
  "contributor": "Supa3939Spider",
  "mods_known": 178,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sat Sep 14 00:14:16 2019"
 },
 "unknown": {
  "Craft Glitterworld Meds": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833402089"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
