### ISSUE TITLE
unknown mods found by Ranaark

### ISSUE THREAD

**Issue by Ranaark** [shakeyourbunny/RWMSDB#531]
{
 "meta": {
  "contributor": "",
  "mods_known": 142,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sun Sep 15 17:12:11 2019"
 },
 "unknown": {
  "Combat Enthusiast's Collection": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1862509294"
  ],
  "Jin-Roh Kerberos Panzer Cop Armor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861644030"
  ],
  "More Hydroponics": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861766385"
  ],
  "[CP] DOOM: Glory Kill Takedown": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1860589645"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
