### ISSUE TITLE
L-Slimes should be after loaded More Mechanoids

### ISSUE THREAD

**Issue by NKSHV** [shakeyourbunny/RWMSDB#533]
https://steamcommunity.com/sharedfiles/filedetails/?id=1206705240&searchtext=L+slimes
https://steamcommunity.com/sharedfiles/filedetails/?id=846222458&searchtext=more+mechanoids

L slimes has more mechanoids integration (adds new mechanoid). If loaded before More Mechanoids, it produces message in log "Should be loaded after more mechanoids". Mod sorter puts l slimes higher than more mechanoids

**Comment by shakeyourbunny** [comment]
should be live, forgot it to close ;D
