### ISSUE TITLE
7 mods

### ISSUE THREAD

**Issue by Kladdey** [shakeyourbunny/RWMSDB#54]
[rwms_unknown_mods_20190503-1422.json.txt](https://github.com/shakeyourbunny/RWMS/files/3141817/rwms_unknown_mods_20190503-1422.json.txt)

**Comment by shakeyourbunny** [comment]
Hi,

I added your missing mods to the database.

Looking at the submitted JSON file, I guess you are not using the most up to date (0.94.0 version of RWMS).

Perhaps you upgrade to it? There is also a windows executable build available.

Have fun!

**Comment by Kladdey** [comment]
Thanks, I didn't notice the update :(

pt., 3 maj 2019, 14:57 użytkownik shakeyourbunny <notifications@github.com>
napisał:
