### ISSUE TITLE
Wrong order - Infinite Turrets & Selected Reconnector

### ISSUE THREAD

**Issue by ColdFusionH3** [shakeyourbunny/RWMSDB#561]
Infinite Turrets (Steam ID: [1553692270](https://steamcommunity.com/sharedfiles/filedetails/?id=1553692270)) must be loaded before Selected Reconnector (Steam ID: [1662438869](https://steamcommunity.com/sharedfiles/filedetails/?id=1662438869)) or Infinite Turrets will not work.

By default, RWMS places Infinite Turrets below Selected Reconnector.

Comment from Infinite Turrets author: 

> When using "Selected Reconnector" ensure that my mod is above it in your modlist. This is to prevent a conflict where my mod stops working.

**Comment by shakeyourbunny** [comment]
Thank you, I fixed the order.
