### ISSUE TITLE
unknown mods found by superlagg

### ISSUE THREAD

**Issue by Superlagg** [shakeyourbunny/RWMSDB#562]
{
 "meta": {
  "contributor": "",
  "mods_known": 267,
  "mods_unknown": 5,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.95.1",
  "time": "Wed Sep 18 08:43:55 2019"
 },
 "unknown": {
  "Cosmic Horrors (CE compatibility patch)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1357967363"
  ],
  "Ejectable Cyptosleep Caskets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1839918172"
  ],
  "Expandable Plants": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1514042242"
  ],
  "Sergals and Gnolls": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\Sergal"
  ],
  "Surgery Armor Fix": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1862332387"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
