### ISSUE TITLE
unknown mods found by kd8lvt

### ISSUE THREAD

**Issue by kd8lvt** [shakeyourbunny/RWMSDB#563]
{
 "meta": {
  "contributor": "kd8lvt",
  "mods_known": 203,
  "mods_unknown": 8,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Wed Sep 18 12:58:39 2019"
 },
 "unknown": {
  "EPOE Patch: Buildable Auxiliary AIs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1770926097"
  ],
  "Fire Treated Wood": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1854329145"
  ],
  "Minecarts: Get Haul'n Update": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861582955"
  ],
  "More Hydroponics": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861766385"
  ],
  "Royal Thrumbos": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865990377"
  ],
  "[EPOE] AI Persona Core Fix: No Berserk": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1163976431"
  ],
  "[O21] Elves": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865535554"
  ],
  "[O21] Goblins": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1863617520"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added, thank you!
