### ISSUE TITLE
unknown mods found by Sandchester

### ISSUE THREAD

**Issue by sandchester** [shakeyourbunny/RWMSDB#564]
{
 "meta": {
  "contributor": "Sandchester",
  "mods_known": 291,
  "mods_unknown": 24,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Wed Sep 18 16:34:09 2019"
 },
 "unknown": {
  "20th Century Weapons Mod (20CW\u041c)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=730433288"
  ],
  "Advanced Shelf Stocking": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1433786924"
  ],
  "Better Electronics": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1555743957"
  ],
  "Combat Enthusiast's Collection": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1862509294"
  ],
  "Draft Notice: A Radio Add-On for RedHorse Furniture": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1555149741"
  ],
  "Forsaken planet": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544699249"
  ],
  "Hotline Miami Music Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1863115711"
  ],
  "Jin-Roh Kerberos Panzer Cop Armor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861644030"
  ],
  "Kurin,_The_Three_Tailed_Fox_zh": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833674577"
  ],
  "Modern Turret Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1477139982"
  ],
  "More Hydroponics": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861766385"
  ],
  "Nanotrasen's Jukebox": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1497110611"
  ],
  "Next Inc. -Apparel": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1850425459"
  ],
  "Portal Turrets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1549883638"
  ],
  "Rain Caller": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1352936813"
  ],
  "Replica Vanometric Power Cells": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1547510568"
  ],
  "Rimrats": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=732346254"
  ],
  "Rimstation 13 a e s t h e t i c mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1545845883"
  ],
  "Save Our Ship (Reloaded): Space Suits": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1782693188"
  ],
  "Steam Light": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1838976414"
  ],
  "Vanilla Bionic Extensions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1418018232"
  ],
  "[CP] British Military Kit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1864033077"
  ],
  "[FSF] Always Rearm Turrets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1848373717"
  ],
  "llCher Wardrobell": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1569824533"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added them, thank you!
