### ISSUE TITLE
unknown mods found by CJVeto

### ISSUE THREAD

**Issue by CJVeto** [shakeyourbunny/RWMSDB#568]
{
 "meta": {
  "contributor": "CJVeto",
  "mods_known": 299,
  "mods_unknown": 6,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Thu Sep 19 06:44:59 2019"
 },
 "unknown": {
  "Adaptive Cassie Storyteller": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1823958161"
  ],
  "Combat Enthusiast's Collection": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1862509294"
  ],
  "Minecarts: Get Haul'n Update": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861582955"
  ],
  "Raise The Roof Cheaply": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1781368087"
  ],
  "[CP] British Military Kit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1864033077"
  ],
  "[Remake] Stockpile Stack Limit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1852323982"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
already all known
