### ISSUE TITLE
Bad sorting order for RJW and extensions.

### ISSUE THREAD

**Issue by bicobus** [shakeyourbunny/RWMSDB#571]
https://github.com/shakeyourbunny/RWMSDB/blob/2d46f317ef0bf12b3056bf04c2e1a424e6768f72/rwmsdb.json#L2338-L2340

Rimjobworld extension and RJW Questionable Ethics are patches to the mod RimJowWorld, not patches to the game itself. As such they should *always* be loaded after the mod they were designed for.

Many mods started to ship with a Manifest.xml file, used by Fluffy's mod manager in order to designate which dependencies needs to comes before themselves. It would be a good idea for RWMS to observe those rules.

**Comment by shakeyourbunny** [comment]
parsing the XML is a planned feature (and the reason for a major overhaul), it predates certain other stuff in the internet ;D

I moved the addon to the gameplay section. Hopefully this will fix it.
