### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by koenderey** [shakeyourbunny/RWMSDB#574]
{
 "meta": {
  "contributor": "",
  "mods_known": 151,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sat Sep 21 14:05:50 2019"
 },
 "unknown": {
  "Gloomy Deco": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865654125"
  ],
  "[CP] British Military Kit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1864033077"
  ],
  "[O21] Elves": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865535554"
  ],
  "[O21] Elves: Faction Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1867068679"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
already added
