### ISSUE TITLE
unknown mods found by CJVeto

### ISSUE THREAD

**Issue by CJVeto** [shakeyourbunny/RWMSDB#576]
{
 "meta": {
  "contributor": "",
  "mods_known": 21,
  "mods_unknown": 11,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sat Sep 21 16:17:29 2019"
 },
 "unknown": {
  "Adaptive Cassie Storyteller": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1823958161"
  ],
  "Combat Enthusiast's Collection": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1862509294"
  ],
  "Gloomy Deco": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865654125"
  ],
  "Jin-Roh Kerberos Panzer Cop Armor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861644030"
  ],
  "Minecarts: Get Haul'n Update": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861582955"
  ],
  "NPDTiers: The Nutrient Paste Expansion Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1864411034"
  ],
  "Raise The Roof Cheaply": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1781368087"
  ],
  "Royal Thrumbos": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865990377"
  ],
  "Weapon Attachments": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1512413945"
  ],
  "[CP] British Military Kit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1864033077"
  ],
  "[Remake] Stockpile Stack Limit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1852323982"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
