### ISSUE TITLE
unknown mods found by john@haverkamp.us

### ISSUE THREAD

**Issue by mothringer** [shakeyourbunny/RWMSDB#58]
{
 "EPOE - rebalance": "not_categorized",
 "Fertile Planet": "not_categorized",
 "Mortar Accuracy": "not_categorized",
 "_contributor": "john@haverkamp.us",
 "time": "Fri May  3 18:48:36 2019"
}

**Comment by shakeyourbunny** [comment]
Hello,

added your contributions, thank you!
