### ISSUE TITLE
unknown mods found by Supa39Spider

### ISSUE THREAD

**Issue by Supa39Spider** [shakeyourbunny/RWMSDB#580]
{
 "meta": {
  "contributor": "",
  "mods_known": 189,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Mon Sep 23 00:41:36 2019"
 },
 "unknown": {
  "Denser Beds": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865290030"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
