### ISSUE TITLE
Unknown mods (CodeOptimist's Assorted Alterations / Storage&Ingredient Filters)

### ISSUE THREAD

**Issue by TwistedMinds2** [shakeyourbunny/RWMSDB#593]
{
 "meta": {
  "contributor": "",
  "mods_known": 161,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Tue Sep 24 12:09:11 2019"
 },
 "unknown": {
  "CodeOptimist's Assorted Alterations": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861437314"
  ],
  "Storage & Ingredient Filters": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1871338921"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
