### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by LunaticNeko** [shakeyourbunny/RWMSDB#594]
{
 "meta": {
  "contributor": "",
  "mods_known": 265,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Wed Sep 25 01:15:57 2019"
 },
 "unknown": {
  "Ingots": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1575967896"
  ],
  "Red Sterile Tile": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1273442199"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
already added
