### ISSUE TITLE
UNKNOWN MODS

### ISSUE THREAD

**Issue by GUYMCAWESOME** [shakeyourbunny/RWMSDB#602]
{
 "meta": {
  "contributor": "",
  "mods_known": 306,
  "mods_unknown": 13,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Tue Sep 24 23:38:08 2019"
 },
 "unknown": {
  "Gloomy Deco": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865654125"
  ],
  "Gloomy Face mk2": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870677788"
  ],
  "Gloomy Hair mk2": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870678335"
  ],
  "Hotline Miami Music Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1863115711"
  ],
  "O21 Races + Combat Extended Compatibility Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1869600129"
  ],
  "Royal Thrumbos": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865990377"
  ],
  "SRTS Expanded Realism Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1846574288"
  ],
  "Save Our Ship (Reincarnated) !!INSTABLE!!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1802846111"
  ],
  "[CP] The DOOM Kit: Classic": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1843130069"
  ],
  "[O21] Elves": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865535554"
  ],
  "[O21] Elves: Faction Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1867068679"
  ],
  "[O21] Goblins": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1863617520"
  ],
  "[O21] Goblins: Faction Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1867068456"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
