### ISSUE TITLE
Unknown mods found by rawrfisher

### ISSUE THREAD

**Issue by rawrfisher** [shakeyourbunny/RWMSDB#611]
{
 "meta": {
  "contributor": "",
  "mods_known": 134,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Wed Sep 25 12:17:12 2019"
 },
 "unknown": {
  "Gloomy Deco": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865654125"
  ],
  "UN-Colony Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1869087753"
  ],
  "[CP] British Military Kit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1864033077"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
