### ISSUE TITLE
unknown mods found by Darwinning

### ISSUE THREAD

**Issue by Darwinning** [shakeyourbunny/RWMSDB#62]
{
 "meta": {
  "contributor": "",
  "mods_known": 265,
  "mods_unknown": 6,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.2",
  "time": "Sat May  4 12:14:51 2019"
 },
 "unknown": {
  "Android tiers CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1386530536"
  ],
  "ETRT: Room Size Tweaks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544557907"
  ],
  "InfestationBait": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541249195"
  ],
  "RePower RBSE Hardcore Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1686938086"
  ],
  "Vegetable Garden Lite": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1698026875"
  ],
  "[SYR] Stone Rebalance": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544076093"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
hi, added your contribution.

thank you!
