### ISSUE TITLE
unknown mods found by Superlagg

### ISSUE THREAD

**Issue by Superlagg** [shakeyourbunny/RWMSDB#63]
{
 "meta": {
  "contributor": "",
  "mods_known": 244,
  "mods_unknown": 33,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.2",
  "time": "Sat May  4 11:43:35 2019"
 },
 "unknown": {
  "2x2 Hydroponics with Sunlamp": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1330587565"
  ],
  "All your base": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=AllYourBase-master"
  ],
  "Arachnophobia CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1357961751"
  ],
  "Call of Cthulhu - Cosmic Horrors - CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1357967363"
  ],
  "Cassandra Hardcore": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1561719529"
  ],
  "CelsiusAndFahrenheit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1421904390"
  ],
  "Climate Cycle++": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1266884568"
  ],
  "Cults CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1357970120"
  ],
  "Equipment Deterioration": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1565674984"
  ],
  "Fire Extinguisher (NF)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1630720769"
  ],
  "Flagstone Cheaper (2 per) V1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1543215657"
  ],
  "GlitterWorld Prime": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=GlitterWorldPrime [R1]"
  ],
  "HarshWorld": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1624126292"
  ],
  "Hydroponic Devilstrand": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1257038785"
  ],
  "Improved Anesthetic": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1720146518"
  ],
  "List Everything": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1706669545"
  ],
  "LongRangePodLauncher": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=819435604"
  ],
  "MyRoom - I want that": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541796376"
  ],
  "Ni'Hal (EPOE Patch)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1544599066"
  ],
  "Ni'Hal Drake Patch 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541581600"
  ],
  "OHU Ships": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=OHU-Dropships-master"
  ],
  "Pawns Play Together": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=961333568"
  ],
  "Phinix": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1620283146"
  ],
  "Rambo Weapons Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1125630361"
  ],
  "Sergals, Gnolls and Lions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1501315350"
  ],
  "Uninspired": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1528893081"
  ],
  "VGP Revised Caffeine": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1666439318"
  ],
  "[1.0] No Simple Raids": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541326422"
  ],
  "[1.0] Walking Problem, the Happening Storyteller 3.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1295107035"
  ],
  "[KV] Weapon Storage Combat Extended Patch - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1711864630"
  ],
  "[WD] Additional RAIDs! 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=954445412"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi,

can you confirm that 

>   "All your base": [
>   "not_categorized",
>   "https://steamcommunity.com/sharedfiles/filedetails/?id=AllYourBase-master"
>  ],

is from https://github.com/RimWorld-CCL-Reborn/AllYourBase ? If not, can you provide the URL where you download this mod? If this mod is available from Steam Workshop, I'd like to know its URL; could not locate it.

**Comment by Superlagg** [comment]
> Hi,
> 
> can you confirm that
> 
> > "All your base": [
> > "not_categorized",
> > "https://steamcommunity.com/sharedfiles/filedetails/?id=AllYourBase-master"
> > ],
> 
> is from https://github.com/RimWorld-CCL-Reborn/AllYourBase ? If not, can you provide the URL where you download this mod? If this mod is available from Steam Workshop, I'd like to know its URL; could not locate it.

I'll confirm that, it is the same mod from that link.

**Comment by shakeyourbunny** [comment]
Then I guessed correctly, enjoy your mods ,-)

Thank you!
