### ISSUE TITLE
unknown mods found by Ridesdragons

### ISSUE THREAD

**Issue by ridesdragons** [shakeyourbunny/RWMSDB#643]
{
 "meta": {
  "contributor": "",
  "mods_known": 163,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Thu Sep 26 02:26:17 2019"
 },
 "unknown": {
  "Better ModMismatch Window": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1872244972"
  ],
  "Gloomy Face mk2": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870677788"
  ],
  "Gloomy Hair mk2": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870678335"
  ]
 },
 "version": 2
}

**Comment by ridesdragons** [comment]
though, frankly, the modmismatch mod doesn't care about load order (can go next to fluffy's mod manager), and gloomy face/hair mk2 can go where mk1 was (and I'm not even sure load order matters for them, either)

**Comment by shakeyourbunny** [comment]
well, I put it already somewhere, but other people also have reported all these mods ;)

Thank you!
