### ISSUE TITLE
unknown mods

### ISSUE THREAD

**Issue by KuroNeko87** [shakeyourbunny/RWMSDB#647]
{
 "meta": {
  "contributor": "",
  "mods_known": 434,
  "mods_unknown": 29,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Fri Sep 27 06:10:51 2019"
 },
 "unknown": {
  "BabyAndChildren CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865752086"
  ],
  "Better ModMismatch Window": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1872244972"
  ],
  "DE Surgeries: Dubs Bad Hygiene": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1871460400"
  ],
  "Escape the Rimworld: Wastelander Branch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870252474"
  ],
  "Expanded Floors: Cupro's Stones Compatibility Patch": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\__LocalCopy_Expanded_Floors_-Cupros_Stone_Compatibility_Patch_-2-9"
  ],
  "Get Out!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1869692724"
  ],
  "Gloomy Face mk2": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870677788"
  ],
  "Gloomy Hair mk2": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870678335"
  ],
  "Housekeeper cat textures": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1871313131"
  ],
  "LT-GardeningRegrown": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1804422724"
  ],
  "Magical Potion Of Medieval": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1834395490"
  ],
  "Max Gain Cap Removal": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1866959462"
  ],
  "Modified World Feature Names": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1872596447"
  ],
  "O21 Races + Combat Extended Compatibility Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1869600129"
  ],
  "PS-Tiberium Rim": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1268312336"
  ],
  "RimOut: NCR uniforms": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1753782862"
  ],
  "SeedsPleaseAddon\u3010ZP\u3011Rice cultivating civilization": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1137255123"
  ],
  "SeedsPleaseAddon\u3010ZP\u3011Zipangu pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1316890469"
  ],
  "UN-Colony Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1869087753"
  ],
  "UnderWhere": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870010563"
  ],
  "Vanilla Armour Expanded: Legs Armour": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873376207"
  ],
  "Vanilla Factions Expanded: Medieval + Combat Extended Compatibility Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1869326792"
  ],
  "Vanilla Fences (Fence Tab)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870822299"
  ],
  "ZARS Core": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1502619368"
  ],
  "[O21] Elves: Faction Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1867068679"
  ],
  "[O21] Enhanced Orbital Beacon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1847127207"
  ],
  "[O21] Goblins: Faction Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1867068456"
  ],
  "[SY4] VFWP Compatibility Patch: Proper Shotguns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1818840661"
  ],
  "[XND] Vanilla-Friendly Battery Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1213894880"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your missing mods, thank you!
