### ISSUE TITLE
rwms_unknown_mods_20190929-1020.json.txt

### ISSUE THREAD

**Issue by NKSHV** [shakeyourbunny/RWMSDB#653]
{
 "meta": {
  "contributor": "",
  "mods_known": 391,
  "mods_unknown": 19,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sun Sep 29 10:20:49 2019"
 },
 "unknown": {
  "Esawa's I CAN PLANT EVERYTHING": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542946846"
  ],
  "Futuristic Plants": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1826002391"
  ],
  "Get Out!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1869692724"
  ],
  "Glass + Lights Extended": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1755160150"
  ],
  "Gloomy Hair mk2": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870678335"
  ],
  "Lulu's Animal Organs": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\LuluAnimalOrgans-1.0.0"
  ],
  "Lulu's Inspiration Chip": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\LuluInspirationChip-1.0.1"
  ],
  "Lulu's Organ Cloning": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\LuluOrganCloning-1.2.1"
  ],
  "MDrugs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1867506097"
  ],
  "Max Gain Cap Removal": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1866959462"
  ],
  "Merp's Pistol Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1464732532"
  ],
  "Merp's Shotgun Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1467013321"
  ],
  "Nootropics": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1781444634"
  ],
  "Power of Energy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1547777789"
  ],
  "Remove Gradual Relations Decay: Patchy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1860686739"
  ],
  "RimSide Recycling": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1825360426"
  ],
  "Sophotronics": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\Sophotronics"
  ],
  "Stockalike Endgame Arsenal": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\StockalikeArms"
  ],
  "Supes Christmas Weapons": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1593279255"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
