### ISSUE TITLE
unknown mods

### ISSUE THREAD

**Issue by DidNotZero** [shakeyourbunny/RWMSDB#663]
{
 "meta": {
  "contributor": "",
  "mods_known": 2,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Mon Sep 30 13:15:43 2019"
 },
 "unknown": {
  "Better ModMismatch Window": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1872244972"
  ],
  "BnC: Shut up, baby!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873232905"
  ],
  "Dynamic Diplomacy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1875168898"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
