### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by archangel5432** [shakeyourbunny/RWMSDB#67]
{
 "meta": {
  "contributor": "",
  "mods_known": 213,
  "mods_unknown": 31,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.2",
  "time": "Sun May  5 15:28:39 2019"
 },
 "unknown": {
  "20th Century Weapons Mod Unofficial 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542206501"
  ],
  "Adeptus Mechanicus Magos Xenobiologis (Playable Eldar)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541515831"
  ],
  "Adeptus Mechanicus Magos Xenobiologis (Playable Orkoids)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541518264"
  ],
  "Adeptus Mechanicus Magos Xenobiologis R1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541499916"
  ],
  "Advanced Hydroponics": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=749150111"
  ],
  "Appearance clothes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1537867047"
  ],
  "CIWS_Weapon [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1493503027"
  ],
  "Craftable Luciferium": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1284354249"
  ],
  "Easily Craftable Components [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1530297431"
  ],
  "Faster Dev Speed": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1579958166"
  ],
  "Flommel [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541255350"
  ],
  "Genetically Engineered Trait": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=__LocalCopy_Genetically Engineered Trait_(8-3)"
  ],
  "Mini Solar Panels": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1528895711"
  ],
  "Monster Mash": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541482356"
  ],
  "RT's Weapon Pack Reloaded (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541374757"
  ],
  "Recycle 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1534883539"
  ],
  "RimBuff": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541242710"
  ],
  "Rimperion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541243129"
  ],
  "Simply Melee Weapons": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541754742"
  ],
  "Small Power Cell [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1530315871"
  ],
  "T-45b Power Armor (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1502931684"
  ],
  "Wob Carry Capacity": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Capacity"
  ],
  "[1.0] Luci heals more!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=965087548"
  ],
  "[1.0] Removable Mt.Rock Roof Patche": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541438898"
  ],
  "[FSF] Carpets of the Rainbow": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=893156099"
  ],
  "[KIR]No Turret Barrels Replacing - More Vanilla Turrets Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1536194712"
  ],
  "[SS]King's slaves": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1545402212"
  ],
  "[T4] Stalin's Weapon Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1515474881"
  ],
  "[XND] Simple Plastic": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1102480398"
  ],
  "\u4e5d\u5c3e\u306e\u72d0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1507522941"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added your mods, have fun playing!
