### ISSUE TITLE
unknown mods found by Midaychi

### ISSUE THREAD

**Issue by Midaychi** [shakeyourbunny/RWMSDB#676]
{
 "meta": {
  "contributor": "",
  "mods_known": 366,
  "mods_unknown": 12,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Wed Oct  2 04:37:48 2019"
 },
 "unknown": {
  "Dynamic Diplomacy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1875168898"
  ],
  "Gone Cooperative": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873115737"
  ],
  "Gone Joyful Traits": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873118928"
  ],
  "Gwen's Definition Patches": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873115086"
  ],
  "Music on the Rim": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1872570102"
  ],
  "Project Pangaea": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1806811908"
  ],
  "Project Pangaea: Free Range": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1850613477"
  ],
  "RimFlix: Anime Loops": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\RimFlix - Anime Loops"
  ],
  "RimFlix: RIM Judged Dredd": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1712121990"
  ],
  "RimSide Recycling": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1825360426"
  ],
  "Simply More Melee": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873462256"
  ],
  "Vanilla Fences (Fence Tab)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870822299"
  ]
 },
 "version": 2
}

**Comment by Midaychi** [comment]
{
 "meta": {
  "contributor": "",
  "mods_known": 358,
  "mods_unknown": 17,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Wed Oct  2 16:56:33 2019"
 },
 "unknown": {
  "Dynamic Diplomacy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1875168898"
  ],
  "EBTools": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1855529560"
  ],
  "Gone Cooperative": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873115737"
  ],
  "Gone Joyful Traits": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873118928"
  ],
  "Gwen's Definition Patches": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873115086"
  ],
  "Micro Designations": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1877972690"
  ],
  "Music on the Rim": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1872570102"
  ],
  "Project Pangaea": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1806811908"
  ],
  "Project Pangaea: Free Range": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1850613477"
  ],
  "Rabbie The Moonrabbit: English Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1877535910"
  ],
  "RimFlix: Anime Loops": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\RimFlix - Anime Loops"
  ],
  "RimFlix: RIM Judged Dredd": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1712121990"
  ],
  "RimSide Recycling": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1825360426"
  ],
  "Simply More Melee": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873462256"
  ],
  "TDBug": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\TDBug"
  ],
  "Vanilla Fences (Fence Tab)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1870822299"
  ],
  "Without Steam": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1878237312"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
