### ISSUE TITLE
unknown mods found by tigartar

### ISSUE THREAD

**Issue by tigartar** [shakeyourbunny/RWMSDB#677]
{
 "meta": {
  "contributor": "tigartar",
  "mods_known": 260,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Thu Oct  3 03:23:32 2019"
 },
  "Better ModMismatch Window": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1872244972"
  ],
  "Dynamic Diplomacy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1875168898"
  ],
  "Magical Freezer": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=935143958"
  ]
 },
 "version": 2
}

**Comment by tigartar** [comment]
Edited out my own made mods that i used to use for sorting purposes

**Comment by shakeyourbunny** [comment]
added 1 mod, JSON was faulty, but I corrected it.
