### ISSUE TITLE
unknown mods found by VileDemon

### ISSUE THREAD

**Issue by VileDemon7** [shakeyourbunny/RWMSDB#678]
{
 "meta": {
  "contributor": "",
  "mods_known": 333,
  "mods_unknown": 7,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Tue Oct  8 20:45:27 2019"
 },
 "unknown": {
  "Dynamic Diplomacy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1875168898"
  ],
  "Kenshi Apparel Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1835771050"
  ],
  "Put in Fences Tab": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1881065117"
  ],
  "Simply More Melee": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1873462256"
  ],
  "Vanilla Furniture Expanded: Production": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632"
  ],
  "Vertibirds": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1876532724"
  ],
  "Won hair_men": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1879950403"
  ]
 },
 "version": 2
}

**Comment by VileDemon7** [comment]
Edit: Added one more.

**Comment by shakeyourbunny** [comment]
all are now known.
