### ISSUE TITLE
Unknown mods found by sTiKyt

### ISSUE THREAD

**Issue by sTiKyt** [shakeyourbunny/RWMSDB#679]
{
 "meta": {
  "contributor": "",
  "mods_known": 130,
  "mods_unknown": 1,
  "os": "linux",
  "rimworld_version": "1.0.2282 rev730",
  "rwms_version": "0.95.1",
  "time": "Thu Oct  3 00:17:23 2019"
 },
 "unknown": {
  "Kenshi Apparel Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1835771050"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
