### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by LunaticNeko** [shakeyourbunny/RWMSDB#680]
{
 "meta": {
  "contributor": "",
  "mods_known": 293,
  "mods_unknown": 5,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Thu Oct  3 10:34:53 2019"
 },
 "unknown": {
  "Dynamic Diplomacy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1875168898"
  ],
  "Elona Imouto Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1863723112"
  ],
  "Ingots": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1575967896"
  ],
  "Red Sterile Tile": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1273442199"
  ],
  "Vertibirds": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1876532724"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
