### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by Harukajunko** [shakeyourbunny/RWMSDB#682]
{
 "meta": {
  "contributor": "Harukajunko",
  "mods_known": 351,
  "mods_unknown": 8,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Thu Oct  3 05:35:52 2019"
 },
 "unknown": {
  "Better ModMismatch Window": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1872244972"
  ],
  "PS-Tiberium Rim": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1268312336"
  ],
  "Refactored Work Priorities": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=774989162"
  ],
  "Vertibirds": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1876532724"
  ],
  "Weapons and Apparels": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1149772329"
  ],
  "\u3010ZP\u3011RCC fuel expansion patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1132812730"
  ],
  "\u3010ZP\u3011Weapons and Apparel": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1148626447"
  ],
  "\u4f8d(Samurai)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1166339900"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
