### ISSUE TITLE
unknown mod(s) found - Vanilla Furniture Expanded: Production

### ISSUE THREAD

**Issue by Reann-Shepard** [shakeyourbunny/RWMSDB#690]
{
 "meta": {
  "contributor": "",
  "mods_known": 100,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Sat Oct  5 18:02:58 2019"
 },
 "unknown": {
  "Vanilla Furniture Expanded: Production": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
