### ISSUE TITLE
unknown mod found by Reteo

### ISSUE THREAD

**Issue by reteo** [shakeyourbunny/RWMSDB#691]
{
 "meta": {
  "contributor": "",
  "mods_known": 133,
  "mods_unknown": 1,
  "os": "linux",
  "rimworld_version": "1.0.2408 rev750",
  "rwms_version": "0.95.1",
  "time": "Sat Oct  5 14:42:50 2019"
 },
 "unknown": {
  "Neutroamine Synthesis": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1563238788"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
