### ISSUE TITLE
unnkown mods from morphine00

### ISSUE THREAD

**Issue by morphine00** [shakeyourbunny/RWMSDB#695]
{
 "meta": {
  "contributor": "",
  "mods_known": 62,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Sun Oct  6 15:55:04 2019"
 },
 "unknown": {
  "Better ModMismatch Window": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1872244972"
  ],
  "Vanilla Furniture Expanded: Production": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
already added.
