### ISSUE TITLE
unknown mods by akymo

### ISSUE THREAD

**Issue by Akymo** [shakeyourbunny/RWMSDB#696]
{
 "meta": {
  "contributor": "akymo",
  "mods_known": 280,
  "mods_unknown": 14,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Tue Oct  8 22:01:46 2019"
 },
 "unknown": {
  "Configurable Texture Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1497484077"
  ],
  "Jayne's Cunning Hat": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1116014098"
  ],
  "Merp's Pistol Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1464732532"
  ],
  "Merp's Shotgun Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1467013321"
  ],
  "Return to Xerigium": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1287205255"
  ],
  "Science Never Stops (Research Only)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=949522884"
  ],
  "TY Female Body /": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1548995767"
  ],
  "TY Female Body and Apparel": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1332248295"
  ],
  "TY Female Body \u6539 /": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1549082450"
  ],
  "TY Female Faces /": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1549933203"
  ],
  "TY Male Body /": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1551743787"
  ],
  "TY Voluptuous Female Body and BasicApparel": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1358936518"
  ],
  "Won hair_men": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1879950403"
  ],
  "[WD] Old Healroot Texture": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1700747293"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
