### ISSUE TITLE
unknown mods by plesry

### ISSUE THREAD

**Issue by plesry** [shakeyourbunny/RWMSDB#697]
{
  "meta": {
   "contributor": "",
   "mods_known": 95,
   "mods_unknown": 5,
   "os": "linux",
   "rimworld_version": "1.0.2408 rev750",
   "rwms_version": "0.95.1",
   "time": "Tue Oct  8 18:48:16 2019"
  },
  "unknown": {
   "Better ModMismatch Window": [
    "not_categorized",
    "https://steamcommunity.com/sharedfiles/filedetails/?id=1872244972"
   ],
   "Faction_Discovery_zh": [
    "not_categorized",
    "https://steamcommunity.com/sharedfiles/filedetails/?id=1782263884"
   ],
   "RimQuest_zh": [
    "not_categorized",
    "https://steamcommunity.com/sharedfiles/filedetails/?id=1805537319"
   ],
   "Set_Up_Camp_zh": [
    "not_categorized",
    "https://steamcommunity.com/sharedfiles/filedetails/?id=1782210304"
   ],
   "Won hair_men": [
    "not_categorized",
    "https://steamcommunity.com/sharedfiles/filedetails/?id=1879950403"
   ]
  },
  "version": 2
 }

**Comment by shakeyourbunny** [comment]
added
