### ISSUE TITLE
unknown mods

### ISSUE THREAD

**Issue by warstoke** [shakeyourbunny/RWMSDB#698]
{
 "meta": {
  "contributor": "",
  "mods_known": 129,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Wed Oct  9 10:19:28 2019"
 },
 "unknown": {
  "Anti Infestation Machine": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1879253940"
  ],
  "Ghost Gear": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1884487332"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
