### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by AngryScandinavian** [shakeyourbunny/RWMSDB#7]
[rwms_unknown_mods_20190413-1457.json.txt](https://github.com/shakeyourbunny/RWMS/files/3076777/rwms_unknown_mods_20190413-1457.json.txt)

**Comment by shakeyourbunny** [comment]
Oh, there is a new feature to transfer the issue, so oh well :)

**Comment by shakeyourbunny** [comment]
Added 22 mods, see 122717efb15dc14178a912c5afb8104aa617b418
