### ISSUE TITLE
rwms unknown mods 20190505

### ISSUE THREAD

**Issue by ju1998ly** [shakeyourbunny/RWMSDB#70]
Thank You for this amazing application, here are some unknown mods, thank you again.

[rwms_unknown_mods_20190505-1058.json.txt]
(https://github.com/shakeyourbunny/RWMSDB/files/3145879/rwms_unknown_mods_20190505-1058.json.txt)

{
 "meta": {
  "contributor": "",
  "mods_known": 207,
  "mods_unknown": 21,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.2",
  "time": "Sun May  5 10:58:16 2019"
 },
 "unknown": {
  "Custom Music": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1091642181"
  ],
  "Exotic's Fine Weaponry": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1370245387"
  ],
  "Glitterworld Medicine + Luciferium + Neutroamine": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1541282228"
  ],
  "HandyUI - Fast Colonist Info": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1653465834"
  ],
  "Infused: Tech Edition": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1568087142"
  ],
  "L-Slimes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1206705240"
  ],
  "MiningCo. Alert speaker": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=848309750"
  ],
  "Old Style Butchery Efficiency [With Mechanoids] (1.0) ": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=952779420"
  ],
  "RT's Weapon Pack [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1538968330"
  ],
  "RoofBomb": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1539350259"
  ],
  "Shields Stand Alone now with Research and Benches": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1630607556"
  ],
  "Siren": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1561823401"
  ],
  "Squad UI Tweaks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1455382219"
  ],
  "Stronger  Quality Scaling (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1206001612"
  ],
  "Weapons+": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1578914181"
  ],
  "[1.0] Combat Shields": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1588616696"
  ],
  "[FSF] Improved Vanometric Power Cells": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1212274603"
  ],
  "[FSF] Lightweight Building Polymer": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=928368180"
  ],
  "[SYR] AK-47": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1510446096"
  ],
  "\u30101.0\u3011Animal straw bed": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1416347393"
  ],
  "\u3010ZP\u3011Sengoku period": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1639686421"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hello,

I added your mods to the database, thank you!
