### ISSUE TITLE
New/unknown mods - Optimization: RAID/Preemptive Strike/Vanilla Hair Expanded/Won hair_women

### ISSUE THREAD

**Issue by Reann-Shepard** [shakeyourbunny/RWMSDB#708]
{
 "meta": {
  "contributor": "",
  "mods_known": 104,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Wed Oct 16 16:42:36 2019"
 },
 "unknown": {
  "Optimization: RAID": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1885551217"
  ],
  "Preemptive Strike": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1890377807"
  ],
  "Vanilla Hair Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256"
  ],
  "Won hair_women": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1886150617"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
already added
