### ISSUE TITLE
unknown mods

### ISSUE THREAD

**Issue by barzopacopalus** [shakeyourbunny/RWMSDB#713]
{
 "meta": {
  "contributor": "",
  "mods_known": 2,
  "mods_unknown": 8,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Thu Oct 17 17:40:44 2019"
 },
 "unknown": {
  "Half-Dragons": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1840577145"
  ],
  "Kurin, General fixes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1869603422"
  ],
  "Medieval Times Nerf": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1835783495"
  ],
  "Preemptive Strike": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1890377807"
  ],
  "Silts Unreligious Pawns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1350551341"
  ],
  "Vanilla Hair Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256"
  ],
  "Won hair_women": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1886150617"
  ],
  "llCher Face V2ll": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1559701679"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
added
