### ISSUE TITLE
Some more unknowns

### ISSUE THREAD

**Issue by ouyin2000** [shakeyourbunny/RWMSDB#75]
{
 "meta": {
  "contributor": "",
  "mods_known": 97,
  "mods_unknown": 9,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.2",
  "time": "Mon May  6 15:53:49 2019"
 },
 "unknown": {
  "Billy's Improved Caravan Formation": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=953429016"
  ],
  "Craftable Plasteel - 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1229704235"
  ],
  "Floored - Yellow and Striped Tiles Only [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1543195051"
  ],
  "Machine gun defense": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1296958152"
  ],
  "Plantable Wild Berries": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1527882769"
  ],
  "Realistic Rooms Lite": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=852142694"
  ],
  "Simple Loom[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1489517427"
  ],
  "Space Ship Chunk Retexture": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1160627004"
  ],
  "Tradable Meals": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1506931205"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hello, added your mod, thank you!
