### ISSUE TITLE
Unknown Mod

### ISSUE THREAD

**Issue by Oggom** [shakeyourbunny/RWMSDB#80]
{
 "meta": {
  "contributor": "",
  "mods_known": 40,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2150 rev801",
  "rwms_version": "0.94.2",
  "time": "Wed May  8 18:00:03 2019"
 },
 "unknown": {
  "Annoyance Remover v0.05": [
   "not_categorized",
   ""
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hello,

added your contribution, have fun!

**Comment by Oggom** [comment]
Thank you! :+1:
