### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by tarak55571** [shakeyourbunny/RWMSDB#82]
Since GitHub doesn't support json files... I converted it to txt

[rwms_unknown_mods_20190509-0337.txt](https://github.com/shakeyourbunny/RWMSDB/files/3161652/rwms_unknown_mods_20190509-0337.txt)

**Comment by shakeyourbunny** [comment]
I know, this is also the reason why the unknown file now ends with .json.txt :D

**Comment by shakeyourbunny** [comment]
Hi, added your mods :-) thank you!
