### ISSUE TITLE
Not Recognized / Unknown Mods

### ISSUE THREAD

**Issue by D3athAn63l** [shakeyourbunny/RWMSDB#84]
{
 "BetterLoading": "not_categorized", { ludeon release : https://ludeon.com/forums/index.php?topic=47892.0 }
 "Cyber Fauna 1.0": "not_categorized",
 "Desynchronized: Tales and News (v1.5.0)": "not_categorized",
 "Dryxsteel": "not_categorized",
 "Enhanced Raiders 1.0": "not_categorized",
 "Expanded Rims": "not_categorized",
 "Faction Blender": "not_categorized",
 "GeneTech": "not_categorized",
 "GlitterWorld Prime": "not_categorized",
 "Gloomy Vanilla": "not_categorized",
 "HelpTab": "not_categorized",
 "Infused: Tech Edition": "not_categorized",
 "Level This! (Version 1.3: Electric Configuloo)": "not_categorized",
 "Loot Boxes": "not_categorized",
 "Mercer's Backpacks (B19)": "not_categorized",
 "Mines": "not_categorized",
 "Mortar Accuracy": "not_categorized",
 "Muh Eggs! [1.0]": "not_categorized",
 "NoJobAuthors": "not_categorized", { ludeon release : https://ludeon.com/forums/index.php?topic=47836.0 }
 "Optimization: Meats": "not_categorized",
 "Quantum Storage 1.0": "not_categorized",
 "RIMMSqol": "not_categorized",
 "Realistic Human Sounds": "not_categorized",
 "Simple FX: Smoke": "not_categorized",
 "Slag Refined Plus": "not_categorized",
 "Sparkling Worlds Extension - BMC Hardcore Patch [1.0]": "not_categorized",
 "Storage Tweaks": "not_categorized", { ludeon release : https://ludeon.com/forums/index.php?topic=41965.msg443286#msg443286 }
 "Synthmeat": "not_categorized",
 "Technology Blueprints": "not_categorized",
 "The Brotherhood Compendium": "not_categorized",
 "Transmution": "not_categorized",
 "Ultraweave": "not_categorized",
 "Un-Limited": "not_categorized",
 "Weapon Artwork Removal": "not_categorized",
 "Weapon Condition Matters, and so does Quality": "not_categorized",
 "[1.0] Tend Whenever": "not_categorized",
 "[NL] Chibi Body": "not_categorized",
 "[NL] Chibi Face Female only": "not_categorized",
 "[NL] Chibi Face Male only": "not_categorized",
 "time": "Fri May 10 01:06:17 2019"
}

Sorry about the clutter <3
Happy Hunting :D

**Comment by Nightliss** [comment]
@D3athAn63l 

you seem to be using an old version of the tool. Some of those mods are already in the database.

**Comment by shakeyourbunny** [comment]
The database is not tied to a specific version, there are some reasons, why duplicates may appear:
- using the old gitlab version which reference the old gitlab DB.
- using a version prior to 0.90 / commit a3c21aa711c8ffce45c2be8165679e477980ef01 on GitLab which broke compatibility with its ancestor. RWMS was originally just a bugfix fork for the other sort script, but soon I have rewritten 80% of the code, so I did a clean restart.
- not proper unicode encoding in the mod names
- mods got a new release and the authors put the new version in the mod name.

This is OT, but I usually want to keep backward compatibility with older releases of my software, but it seems wiser to do once in a while a clean cut. Expect this to happen with during the Tweaks release to intentionally break all old versions of the script.

Just checked out the old Gitlab repo, there are still issue reports though I clearly stated there that the project moved on. Will add these issues, but I'll lock there the issue tracker.

@D3athAn63l : will inte

**Comment by shakeyourbunny** [comment]
Added your new missing mods. thank you!
