### ISSUE TITLE
Not_Categorized

### ISSUE THREAD

**Issue by D3athAn63l** [shakeyourbunny/RWMSDB#88]
{
 "meta": {
  "contributor": "",
  "mods_known": 160,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.3",
  "time": "Fri May 10 22:36:47 2019"
 },
 "unknown": {
  "Auto Recycling[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1440625499"
  ]
 },
 "version": 2
}

I've update to the new version since the last once :D

**Comment by shakeyourbunny** [comment]
Hello, added your new missing mod :-)
