### ISSUE TITLE
Unknown mods update

### ISSUE THREAD

**Issue by axelfoxy** [shakeyourbunny/RWMSDB#9]
[rwms_unknown_mods_20190417-2025.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3091028/rwms_unknown_mods_20190417-2025.json.txt)

Some are not 1.0 compatible and was not enabled in my list I'im using mod manager for load order, so not sure if its using the same file as default config?)

**Comment by shakeyourbunny** [comment]
The mod sorter does not care what RimWorld release it is working with, it only sees the mods in the config file.

**Comment by shakeyourbunny** [comment]
added your contributions to the database, thank you!

**Comment by axelfoxy** [comment]
Had a couple of red lines before, now nothing yaay :D thanks
Still loads for ages.. but meh..
