### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by Radical-Dragon** [shakeyourbunny/RWMSDB#91]
{
 "meta": {
  "contributor": "",
  "mods_known": 215,
  "mods_unknown": 8,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.3",
  "time": "Fri May 10 17:03:23 2019"
 },
 "unknown": {
  "Bad Hygiene Lite": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1736051948"
  ],
  "Galaxy News Radio": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1527291019"
  ],
  "Marine Armor Materials": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1638630888"
  ],
  "Spartan Foundry Warcraft": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1737394695"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hello, added you mods. thank you!
