### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by JonasScheirs** [shakeyourbunny/RWMSDB#92]
{
 "meta": {
  "contributor": "",
  "mods_known": 202,
  "mods_unknown": 28,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.2",
  "time": "Sat May 11 11:58:52 2019"
 },
 "unknown": {
  "AlienFaces": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1551109143"
  ],
  "Ancient Rim - Mediterran Factions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1734664809"
  ],
  "Ancient Rim - SPQRim": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1734141653"
  ],
  "Ancient Rim - core": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1734135259"
  ],
  "Arctic SE Cleaning Bot": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1668827073"
  ],
  "Arctic SE Hauling Bot": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1667269743"
  ],
  "Base Robots Expansion": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1680426495"
  ],
  "Definitely More Cannons - Turret Extension Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1556755412"
  ],
  "Delsin53's HD Terrain Texture Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1292715618"
  ],
  "MMX6 Mining Robot": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1666140747"
  ],
  "Mechanoid Figures[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1498599663"
  ],
  "Pawn Badge - (MISC) Job Icons": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1734233154"
  ],
  "Plant Human": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1572026865"
  ],
  "Praise the Emperor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1659313040"
  ],
  "RoboJack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1668774441"
  ],
  "Sheep (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1207701204"
  ],
  "Silts Radio": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1489320417"
  ],
  "Star Wars Slave Bikini Outfit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1666489638"
  ],
  "Suppression": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1421919369"
  ],
  "TY Slender Female Body for B19/1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1555543738"
  ],
  "Warhammer: Deathjacks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1733501512"
  ],
  "[1.0] Cigarettes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1550446824"
  ],
  "[1.0] Desperades": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1557052794"
  ],
  "[1.0] RimWorld Minions V7.2": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1565657439"
  ],
  "[B19]GW-hair": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1352123439"
  ],
  "[Cab's]Beat The Meat 3.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=946791460"
  ],
  "asari alteration": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1547988615"
  ],
  "dianne's defaults - Facial Stuff [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1545855483"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi, added your contribution, thank you!
