### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by Japan2Canada** [shakeyourbunny/RWMSDB#94]
{
 "meta": {
  "contributor": "",
  "mods_known": 156,
  "mods_unknown": 6,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.4",
  "time": "Sat May 11 03:06:58 2019"
 },
 "unknown": {
  "Apex: Rimworld Legends CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1706516757"
  ],
  "Better Grassy Biomes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1532092631"
  ],
  "Flora": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1524280826"
  ],
  "Hats Display Selection[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1542291825"
  ],
  "Pawn Badge - (MISC) Job Icons": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1734233154"
  ],
  "Rimsenal - Enhanced Vanilla + Combat Extended Compatibility Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1733275147"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment]
Hi, added your contribution. thank you!
