### ISSUE TITLE
Unknown Mods

### ISSUE THREAD

**Issue by Theutus1** [shakeyourbunny/RWMSDB#95]
{
 "Animal Collab Project": "not_categorized",
 "HolyWasher": "not_categorized",
 "Matching Embrasures": "not_categorized",
 "[1.0] Combat Shields": "not_categorized",
 "[FSF] Carpets of the Rainbow": "not_categorized",
 "time": "Sat May 11 15:58:34 2019"
}

**Comment by shakeyourbunny** [comment]
Hallo, added your contributions. thank you!
