### ISSUE TITLE
RPG Style Inventory CE patch should be loaded after RPG style inventory

### ISSUE THREAD

**Issue by jpc0** [shakeyourbunny/RWMSDB#98]
The title pretty much says it all. RPG style inventory is loaded after the RPG style inventory CE patch when the patch creator specifically states it should be in the other order.

So the correct order:

Combat Extended
RPG Style Inventory
RPG Style Inventory CE patch

**Comment by shakeyourbunny** [comment]
fixed now.

Did I already say that Combat Extended should conform to the rest of the game instead of forcing its will onto every other aspect of the game? :)

**Comment by jpc0** [comment]
I know right. Thanks for the great work man.
